package com.titansmasher.taptitansoptimizer.Model.RawSave.AbilityClasses;

import com.titansmasher.taptitansoptimizer.Helpers.GenericHelpers;
import com.titansmasher.taptitansoptimizer.Model.RawSave.Abstracts.AbilityData;

import org.json.JSONObject;

/**
 * Created by Danny on 22/10/2016.
 */

public class AbilityLevels extends AbilityData<Integer> {
    public AbilityLevels(JSONObject obj) {
        if (obj == null) {
            populateFromNull();
            return;
        }
        this.A1 = GenericHelpers.getIntSafe(obj, A1_KEY);
        this.A2 = GenericHelpers.getIntSafe(obj, A2_KEY);
        this.A3 = GenericHelpers.getIntSafe(obj, A3_KEY);
        this.A4 = GenericHelpers.getIntSafe(obj, A4_KEY);
        this.A5 = GenericHelpers.getIntSafe(obj, A5_KEY);
        this.A6 = GenericHelpers.getIntSafe(obj, A6_KEY);
        this.A7 = GenericHelpers.getIntSafe(obj, A7_KEY);
        this.A8 = GenericHelpers.getIntSafe(obj, A8_KEY);
        this.A9 = GenericHelpers.getIntSafe(obj, A9_KEY);
        this.A10 = GenericHelpers.getIntSafe(obj, A10_KEY);
        this.A11 = GenericHelpers.getIntSafe(obj, A11_KEY);
        this.A12 = GenericHelpers.getIntSafe(obj, A12_KEY);
        this.A13 = GenericHelpers.getIntSafe(obj, A13_KEY);
        this.A14 = GenericHelpers.getIntSafe(obj, A14_KEY);
        this.A15 = GenericHelpers.getIntSafe(obj, A15_KEY);
        this.A16 = GenericHelpers.getIntSafe(obj, A16_KEY);
        this.A17 = GenericHelpers.getIntSafe(obj, A17_KEY);
        this.A18 = GenericHelpers.getIntSafe(obj, A18_KEY);
        this.A19 = GenericHelpers.getIntSafe(obj, A19_KEY);
        this.A20 = GenericHelpers.getIntSafe(obj, A20_KEY);
        this.A21 = GenericHelpers.getIntSafe(obj, A21_KEY);
        this.A22 = GenericHelpers.getIntSafe(obj, A22_KEY);
        this.A23 = GenericHelpers.getIntSafe(obj, A23_KEY);
        this.A24 = GenericHelpers.getIntSafe(obj, A24_KEY);
        this.A25 = GenericHelpers.getIntSafe(obj, A25_KEY);
        this.A26 = GenericHelpers.getIntSafe(obj, A26_KEY);
        this.A27 = GenericHelpers.getIntSafe(obj, A27_KEY);
        this.A28 = GenericHelpers.getIntSafe(obj, A28_KEY);
        this.A29 = GenericHelpers.getIntSafe(obj, A29_KEY);
        this.A30 = GenericHelpers.getIntSafe(obj, A30_KEY);
        this.A31 = GenericHelpers.getIntSafe(obj, A31_KEY);
        this.A32 = GenericHelpers.getIntSafe(obj, A32_KEY);
        this.A33 = GenericHelpers.getIntSafe(obj, A33_KEY);
        this.A34 = GenericHelpers.getIntSafe(obj, A34_KEY);
        this.A35 = GenericHelpers.getIntSafe(obj, A35_KEY);
        this.A36 = GenericHelpers.getIntSafe(obj, A36_KEY);
        this.A37 = GenericHelpers.getIntSafe(obj, A37_KEY);
        this.A38 = GenericHelpers.getIntSafe(obj, A38_KEY);
        this.A39 = GenericHelpers.getIntSafe(obj, A39_KEY);
        this.A40 = GenericHelpers.getIntSafe(obj, A40_KEY);
        this.A41 = GenericHelpers.getIntSafe(obj, A41_KEY);
        this.A42 = GenericHelpers.getIntSafe(obj, A42_KEY);
        this.A43 = GenericHelpers.getIntSafe(obj, A43_KEY);
        this.A44 = GenericHelpers.getIntSafe(obj, A44_KEY);
        this.A45 = GenericHelpers.getIntSafe(obj, A45_KEY);
        this.A46 = GenericHelpers.getIntSafe(obj, A46_KEY);
        this.A47 = GenericHelpers.getIntSafe(obj, A47_KEY);
        this.A48 = GenericHelpers.getIntSafe(obj, A48_KEY);
        this.A49 = GenericHelpers.getIntSafe(obj, A49_KEY);
        this.A50 = GenericHelpers.getIntSafe(obj, A50_KEY);
        this.A51 = GenericHelpers.getIntSafe(obj, A51_KEY);
        this.A52 = GenericHelpers.getIntSafe(obj, A52_KEY);
        this.A53 = GenericHelpers.getIntSafe(obj, A53_KEY);
        this.A54 = GenericHelpers.getIntSafe(obj, A54_KEY);
        this.A55 = GenericHelpers.getIntSafe(obj, A55_KEY);
        this.A56 = GenericHelpers.getIntSafe(obj, A56_KEY);
        this.A57 = GenericHelpers.getIntSafe(obj, A57_KEY);
        this.A58 = GenericHelpers.getIntSafe(obj, A58_KEY);
        this.A59 = GenericHelpers.getIntSafe(obj, A59_KEY);
        this.A60 = GenericHelpers.getIntSafe(obj, A60_KEY);
        this.A61 = GenericHelpers.getIntSafe(obj, A61_KEY);
        this.A62 = GenericHelpers.getIntSafe(obj, A62_KEY);
        this.A63 = GenericHelpers.getIntSafe(obj, A63_KEY);
        this.A64 = GenericHelpers.getIntSafe(obj, A64_KEY);
        this.A65 = GenericHelpers.getIntSafe(obj, A65_KEY);
        this.A66 = GenericHelpers.getIntSafe(obj, A66_KEY);
        this.A67 = GenericHelpers.getIntSafe(obj, A67_KEY);
        this.A68 = GenericHelpers.getIntSafe(obj, A68_KEY);
        this.A69 = GenericHelpers.getIntSafe(obj, A69_KEY);
        this.A70 = GenericHelpers.getIntSafe(obj, A70_KEY);
        this.A71 = GenericHelpers.getIntSafe(obj, A71_KEY);
        this.A72 = GenericHelpers.getIntSafe(obj, A72_KEY);
        this.A73 = GenericHelpers.getIntSafe(obj, A73_KEY);
        this.A74 = GenericHelpers.getIntSafe(obj, A74_KEY);
        this.A75 = GenericHelpers.getIntSafe(obj, A75_KEY);
        this.A76 = GenericHelpers.getIntSafe(obj, A76_KEY);
        this.A77 = GenericHelpers.getIntSafe(obj, A77_KEY);
        this.A78 = GenericHelpers.getIntSafe(obj, A78_KEY);
        this.A79 = GenericHelpers.getIntSafe(obj, A79_KEY);
        this.A80 = GenericHelpers.getIntSafe(obj, A80_KEY);
        this.A81 = GenericHelpers.getIntSafe(obj, A81_KEY);
        this.A82 = GenericHelpers.getIntSafe(obj, A82_KEY);
        this.A83 = GenericHelpers.getIntSafe(obj, A83_KEY);
        this.A84 = GenericHelpers.getIntSafe(obj, A84_KEY);
        this.A85 = GenericHelpers.getIntSafe(obj, A85_KEY);
        this.A86 = GenericHelpers.getIntSafe(obj, A86_KEY);
        this.A87 = GenericHelpers.getIntSafe(obj, A87_KEY);
        this.A88 = GenericHelpers.getIntSafe(obj, A88_KEY);
        this.A89 = GenericHelpers.getIntSafe(obj, A89_KEY);
        this.A90 = GenericHelpers.getIntSafe(obj, A90_KEY);
        this.A91 = GenericHelpers.getIntSafe(obj, A91_KEY);
        this.A92 = GenericHelpers.getIntSafe(obj, A92_KEY);
        this.A93 = GenericHelpers.getIntSafe(obj, A93_KEY);
        this.A94 = GenericHelpers.getIntSafe(obj, A94_KEY);
        this.A95 = GenericHelpers.getIntSafe(obj, A95_KEY);
        this.A96 = GenericHelpers.getIntSafe(obj, A96_KEY);
        this.A97 = GenericHelpers.getIntSafe(obj, A97_KEY);
        this.A98 = GenericHelpers.getIntSafe(obj, A98_KEY);
        this.A99 = GenericHelpers.getIntSafe(obj, A99_KEY);
        this.A100 = GenericHelpers.getIntSafe(obj, A100_KEY);
        this.A101 = GenericHelpers.getIntSafe(obj, A101_KEY);
        this.A102 = GenericHelpers.getIntSafe(obj, A102_KEY);
        this.A103 = GenericHelpers.getIntSafe(obj, A103_KEY);
        this.A104 = GenericHelpers.getIntSafe(obj, A104_KEY);
        this.A105 = GenericHelpers.getIntSafe(obj, A105_KEY);
        this.A106 = GenericHelpers.getIntSafe(obj, A106_KEY);
        this.A107 = GenericHelpers.getIntSafe(obj, A107_KEY);
        this.A108 = GenericHelpers.getIntSafe(obj, A108_KEY);
        this.A109 = GenericHelpers.getIntSafe(obj, A109_KEY);
        this.A110 = GenericHelpers.getIntSafe(obj, A110_KEY);
        this.A111 = GenericHelpers.getIntSafe(obj, A111_KEY);
        this.A112 = GenericHelpers.getIntSafe(obj, A112_KEY);
        this.A113 = GenericHelpers.getIntSafe(obj, A113_KEY);
        this.A114 = GenericHelpers.getIntSafe(obj, A114_KEY);
        this.A115 = GenericHelpers.getIntSafe(obj, A115_KEY);
        this.A116 = GenericHelpers.getIntSafe(obj, A116_KEY);
        this.A117 = GenericHelpers.getIntSafe(obj, A117_KEY);
        this.A118 = GenericHelpers.getIntSafe(obj, A118_KEY);
        this.A119 = GenericHelpers.getIntSafe(obj, A119_KEY);
        this.A120 = GenericHelpers.getIntSafe(obj, A120_KEY);
        this.A121 = GenericHelpers.getIntSafe(obj, A121_KEY);
        this.A122 = GenericHelpers.getIntSafe(obj, A122_KEY);
        this.A123 = GenericHelpers.getIntSafe(obj, A123_KEY);
        this.A124 = GenericHelpers.getIntSafe(obj, A124_KEY);
        this.A125 = GenericHelpers.getIntSafe(obj, A125_KEY);
        this.A126 = GenericHelpers.getIntSafe(obj, A126_KEY);
        this.A127 = GenericHelpers.getIntSafe(obj, A127_KEY);
        this.A128 = GenericHelpers.getIntSafe(obj, A128_KEY);
        this.A129 = GenericHelpers.getIntSafe(obj, A129_KEY);
        this.A130 = GenericHelpers.getIntSafe(obj, A130_KEY);
        this.A131 = GenericHelpers.getIntSafe(obj, A131_KEY);
        this.A132 = GenericHelpers.getIntSafe(obj, A132_KEY);
        this.A133 = GenericHelpers.getIntSafe(obj, A133_KEY);
        this.A134 = GenericHelpers.getIntSafe(obj, A134_KEY);
        this.A135 = GenericHelpers.getIntSafe(obj, A135_KEY);
        this.A136 = GenericHelpers.getIntSafe(obj, A136_KEY);
        this.A137 = GenericHelpers.getIntSafe(obj, A137_KEY);
        this.A138 = GenericHelpers.getIntSafe(obj, A138_KEY);
        this.A139 = GenericHelpers.getIntSafe(obj, A139_KEY);
        this.A140 = GenericHelpers.getIntSafe(obj, A140_KEY);
        this.A141 = GenericHelpers.getIntSafe(obj, A141_KEY);
        this.A142 = GenericHelpers.getIntSafe(obj, A142_KEY);
        this.A143 = GenericHelpers.getIntSafe(obj, A143_KEY);
        this.A144 = GenericHelpers.getIntSafe(obj, A144_KEY);
        this.A145 = GenericHelpers.getIntSafe(obj, A145_KEY);
        this.A146 = GenericHelpers.getIntSafe(obj, A146_KEY);
        this.A147 = GenericHelpers.getIntSafe(obj, A147_KEY);
        this.A148 = GenericHelpers.getIntSafe(obj, A148_KEY);
        this.A149 = GenericHelpers.getIntSafe(obj, A149_KEY);
        this.A150 = GenericHelpers.getIntSafe(obj, A150_KEY);
        this.A151 = GenericHelpers.getIntSafe(obj, A151_KEY);
        this.A152 = GenericHelpers.getIntSafe(obj, A152_KEY);
        this.A153 = GenericHelpers.getIntSafe(obj, A153_KEY);
        this.A154 = GenericHelpers.getIntSafe(obj, A154_KEY);
        this.A155 = GenericHelpers.getIntSafe(obj, A155_KEY);
        this.A156 = GenericHelpers.getIntSafe(obj, A156_KEY);
        this.A157 = GenericHelpers.getIntSafe(obj, A157_KEY);
        this.A158 = GenericHelpers.getIntSafe(obj, A158_KEY);
        this.A159 = GenericHelpers.getIntSafe(obj, A159_KEY);
        this.A160 = GenericHelpers.getIntSafe(obj, A160_KEY);
        this.A161 = GenericHelpers.getIntSafe(obj, A161_KEY);
        this.A162 = GenericHelpers.getIntSafe(obj, A162_KEY);
        this.A163 = GenericHelpers.getIntSafe(obj, A163_KEY);
        this.A164 = GenericHelpers.getIntSafe(obj, A164_KEY);
        this.A165 = GenericHelpers.getIntSafe(obj, A165_KEY);
        this.A166 = GenericHelpers.getIntSafe(obj, A166_KEY);
        this.A167 = GenericHelpers.getIntSafe(obj, A167_KEY);
        this.A168 = GenericHelpers.getIntSafe(obj, A168_KEY);
        this.A169 = GenericHelpers.getIntSafe(obj, A169_KEY);
        this.A170 = GenericHelpers.getIntSafe(obj, A170_KEY);
        this.A171 = GenericHelpers.getIntSafe(obj, A171_KEY);
        this.A172 = GenericHelpers.getIntSafe(obj, A172_KEY);
        this.A173 = GenericHelpers.getIntSafe(obj, A173_KEY);
        this.A174 = GenericHelpers.getIntSafe(obj, A174_KEY);
        this.A175 = GenericHelpers.getIntSafe(obj, A175_KEY);
        this.A176 = GenericHelpers.getIntSafe(obj, A176_KEY);
        this.A177 = GenericHelpers.getIntSafe(obj, A177_KEY);
        this.A178 = GenericHelpers.getIntSafe(obj, A178_KEY);
        this.A179 = GenericHelpers.getIntSafe(obj, A179_KEY);
        this.A180 = GenericHelpers.getIntSafe(obj, A180_KEY);
        this.A181 = GenericHelpers.getIntSafe(obj, A181_KEY);
        this.A182 = GenericHelpers.getIntSafe(obj, A182_KEY);
        this.A183 = GenericHelpers.getIntSafe(obj, A183_KEY);
        this.A184 = GenericHelpers.getIntSafe(obj, A184_KEY);
        this.A185 = GenericHelpers.getIntSafe(obj, A185_KEY);
        this.A186 = GenericHelpers.getIntSafe(obj, A186_KEY);
        this.A187 = GenericHelpers.getIntSafe(obj, A187_KEY);
        this.A188 = GenericHelpers.getIntSafe(obj, A188_KEY);
        this.A189 = GenericHelpers.getIntSafe(obj, A189_KEY);
        this.A190 = GenericHelpers.getIntSafe(obj, A190_KEY);
        this.A191 = GenericHelpers.getIntSafe(obj, A191_KEY);
        this.A192 = GenericHelpers.getIntSafe(obj, A192_KEY);
        this.A193 = GenericHelpers.getIntSafe(obj, A193_KEY);
        this.A194 = GenericHelpers.getIntSafe(obj, A194_KEY);
        this.A195 = GenericHelpers.getIntSafe(obj, A195_KEY);
        this.A196 = GenericHelpers.getIntSafe(obj, A196_KEY);
        this.A197 = GenericHelpers.getIntSafe(obj, A197_KEY);
        this.A198 = GenericHelpers.getIntSafe(obj, A198_KEY);
        this.A199 = GenericHelpers.getIntSafe(obj, A199_KEY);
        this.A200 = GenericHelpers.getIntSafe(obj, A200_KEY);
        this.A201 = GenericHelpers.getIntSafe(obj, A201_KEY);
        this.A202 = GenericHelpers.getIntSafe(obj, A202_KEY);
        this.A203 = GenericHelpers.getIntSafe(obj, A203_KEY);
        this.A204 = GenericHelpers.getIntSafe(obj, A204_KEY);
        this.A205 = GenericHelpers.getIntSafe(obj, A205_KEY);
        this.A206 = GenericHelpers.getIntSafe(obj, A206_KEY);
        this.A207 = GenericHelpers.getIntSafe(obj, A207_KEY);
        this.A208 = GenericHelpers.getIntSafe(obj, A208_KEY);
        this.A209 = GenericHelpers.getIntSafe(obj, A209_KEY);
        this.A210 = GenericHelpers.getIntSafe(obj, A210_KEY);
        this.A211 = GenericHelpers.getIntSafe(obj, A211_KEY);
        this.A212 = GenericHelpers.getIntSafe(obj, A212_KEY);
        this.A213 = GenericHelpers.getIntSafe(obj, A213_KEY);
        this.A214 = GenericHelpers.getIntSafe(obj, A214_KEY);
        this.A215 = GenericHelpers.getIntSafe(obj, A215_KEY);
        this.A216 = GenericHelpers.getIntSafe(obj, A216_KEY);
        this.A217 = GenericHelpers.getIntSafe(obj, A217_KEY);
        this.A218 = GenericHelpers.getIntSafe(obj, A218_KEY);
        this.A219 = GenericHelpers.getIntSafe(obj, A219_KEY);
        this.A220 = GenericHelpers.getIntSafe(obj, A220_KEY);
        this.A221 = GenericHelpers.getIntSafe(obj, A221_KEY);
        this.A222 = GenericHelpers.getIntSafe(obj, A222_KEY);
        this.A223 = GenericHelpers.getIntSafe(obj, A223_KEY);
        this.A224 = GenericHelpers.getIntSafe(obj, A224_KEY);
        this.A225 = GenericHelpers.getIntSafe(obj, A225_KEY);
        this.A226 = GenericHelpers.getIntSafe(obj, A226_KEY);
        this.A227 = GenericHelpers.getIntSafe(obj, A227_KEY);
        this.A228 = GenericHelpers.getIntSafe(obj, A228_KEY);
        this.A229 = GenericHelpers.getIntSafe(obj, A229_KEY);
        this.A230 = GenericHelpers.getIntSafe(obj, A230_KEY);
        this.A231 = GenericHelpers.getIntSafe(obj, A231_KEY);
        this.A903 = GenericHelpers.getIntSafe(obj, A903_KEY);
        this.A904 = GenericHelpers.getIntSafe(obj, A904_KEY);
        this.A905 = GenericHelpers.getIntSafe(obj, A905_KEY);
        this.A902 = GenericHelpers.getIntSafe(obj, A902_KEY);
        this.A906 = GenericHelpers.getIntSafe(obj, A906_KEY);
        this.A907 = GenericHelpers.getIntSafe(obj, A907_KEY);
        this.A901 = GenericHelpers.getIntSafe(obj, A901_KEY);
        this.A908 = GenericHelpers.getIntSafe(obj, A908_KEY);
        this.A909 = GenericHelpers.getIntSafe(obj, A909_KEY);
        this.A910 = GenericHelpers.getIntSafe(obj, A910_KEY);
        this.A911 = GenericHelpers.getIntSafe(obj, A911_KEY);
        this.A912 = GenericHelpers.getIntSafe(obj, A912_KEY);
        this.A913 = GenericHelpers.getIntSafe(obj, A913_KEY);
        this.A914 = GenericHelpers.getIntSafe(obj, A914_KEY);
        this.A915 = GenericHelpers.getIntSafe(obj, A915_KEY);
        this.A916 = GenericHelpers.getIntSafe(obj, A916_KEY);
        this.A917 = GenericHelpers.getIntSafe(obj, A917_KEY);
        this.A918 = GenericHelpers.getIntSafe(obj, A918_KEY);
        this.A919 = GenericHelpers.getIntSafe(obj, A919_KEY);
        this.A920 = GenericHelpers.getIntSafe(obj, A920_KEY);
        this.A921 = GenericHelpers.getIntSafe(obj, A921_KEY);
        this.A922 = GenericHelpers.getIntSafe(obj, A922_KEY);
    }

    private void populateFromNull() {
        this.A1 = 0;
        this.A2 = 0;
        this.A3 = 0;
        this.A4 = 0;
        this.A5 = 0;
        this.A6 = 0;
        this.A7 = 0;
        this.A8 = 0;
        this.A9 = 0;
        this.A10 = 0;
        this.A11 = 0;
        this.A12 = 0;
        this.A13 = 0;
        this.A14 = 0;
        this.A15 = 0;
        this.A16 = 0;
        this.A17 = 0;
        this.A18 = 0;
        this.A19 = 0;
        this.A20 = 0;
        this.A21 = 0;
        this.A22 = 0;
        this.A23 = 0;
        this.A24 = 0;
        this.A25 = 0;
        this.A26 = 0;
        this.A27 = 0;
        this.A28 = 0;
        this.A29 = 0;
        this.A30 = 0;
        this.A31 = 0;
        this.A32 = 0;
        this.A33 = 0;
        this.A34 = 0;
        this.A35 = 0;
        this.A36 = 0;
        this.A37 = 0;
        this.A38 = 0;
        this.A39 = 0;
        this.A40 = 0;
        this.A41 = 0;
        this.A42 = 0;
        this.A43 = 0;
        this.A44 = 0;
        this.A45 = 0;
        this.A46 = 0;
        this.A47 = 0;
        this.A48 = 0;
        this.A49 = 0;
        this.A50 = 0;
        this.A51 = 0;
        this.A52 = 0;
        this.A53 = 0;
        this.A54 = 0;
        this.A55 = 0;
        this.A56 = 0;
        this.A57 = 0;
        this.A58 = 0;
        this.A59 = 0;
        this.A60 = 0;
        this.A61 = 0;
        this.A62 = 0;
        this.A63 = 0;
        this.A64 = 0;
        this.A65 = 0;
        this.A66 = 0;
        this.A67 = 0;
        this.A68 = 0;
        this.A69 = 0;
        this.A70 = 0;
        this.A71 = 0;
        this.A72 = 0;
        this.A73 = 0;
        this.A74 = 0;
        this.A75 = 0;
        this.A76 = 0;
        this.A77 = 0;
        this.A78 = 0;
        this.A79 = 0;
        this.A80 = 0;
        this.A81 = 0;
        this.A82 = 0;
        this.A83 = 0;
        this.A84 = 0;
        this.A85 = 0;
        this.A86 = 0;
        this.A87 = 0;
        this.A88 = 0;
        this.A89 = 0;
        this.A90 = 0;
        this.A91 = 0;
        this.A92 = 0;
        this.A93 = 0;
        this.A94 = 0;
        this.A95 = 0;
        this.A96 = 0;
        this.A97 = 0;
        this.A98 = 0;
        this.A99 = 0;
        this.A100 = 0;
        this.A101 = 0;
        this.A102 = 0;
        this.A103 = 0;
        this.A104 = 0;
        this.A105 = 0;
        this.A106 = 0;
        this.A107 = 0;
        this.A108 = 0;
        this.A109 = 0;
        this.A110 = 0;
        this.A111 = 0;
        this.A112 = 0;
        this.A113 = 0;
        this.A114 = 0;
        this.A115 = 0;
        this.A116 = 0;
        this.A117 = 0;
        this.A118 = 0;
        this.A119 = 0;
        this.A120 = 0;
        this.A121 = 0;
        this.A122 = 0;
        this.A123 = 0;
        this.A124 = 0;
        this.A125 = 0;
        this.A126 = 0;
        this.A127 = 0;
        this.A128 = 0;
        this.A129 = 0;
        this.A130 = 0;
        this.A131 = 0;
        this.A132 = 0;
        this.A133 = 0;
        this.A134 = 0;
        this.A135 = 0;
        this.A136 = 0;
        this.A137 = 0;
        this.A138 = 0;
        this.A139 = 0;
        this.A140 = 0;
        this.A141 = 0;
        this.A142 = 0;
        this.A143 = 0;
        this.A144 = 0;
        this.A145 = 0;
        this.A146 = 0;
        this.A147 = 0;
        this.A148 = 0;
        this.A149 = 0;
        this.A150 = 0;
        this.A151 = 0;
        this.A152 = 0;
        this.A153 = 0;
        this.A154 = 0;
        this.A155 = 0;
        this.A156 = 0;
        this.A157 = 0;
        this.A158 = 0;
        this.A159 = 0;
        this.A160 = 0;
        this.A161 = 0;
        this.A162 = 0;
        this.A163 = 0;
        this.A164 = 0;
        this.A165 = 0;
        this.A166 = 0;
        this.A167 = 0;
        this.A168 = 0;
        this.A169 = 0;
        this.A170 = 0;
        this.A171 = 0;
        this.A172 = 0;
        this.A173 = 0;
        this.A174 = 0;
        this.A175 = 0;
        this.A176 = 0;
        this.A177 = 0;
        this.A178 = 0;
        this.A179 = 0;
        this.A180 = 0;
        this.A181 = 0;
        this.A182 = 0;
        this.A183 = 0;
        this.A184 = 0;
        this.A185 = 0;
        this.A186 = 0;
        this.A187 = 0;
        this.A188 = 0;
        this.A189 = 0;
        this.A190 = 0;
        this.A191 = 0;
        this.A192 = 0;
        this.A193 = 0;
        this.A194 = 0;
        this.A195 = 0;
        this.A196 = 0;
        this.A197 = 0;
        this.A198 = 0;
        this.A199 = 0;
        this.A200 = 0;
        this.A201 = 0;
        this.A202 = 0;
        this.A203 = 0;
        this.A204 = 0;
        this.A205 = 0;
        this.A206 = 0;
        this.A207 = 0;
        this.A208 = 0;
        this.A209 = 0;
        this.A210 = 0;
        this.A211 = 0;
        this.A212 = 0;
        this.A213 = 0;
        this.A214 = 0;
        this.A215 = 0;
        this.A216 = 0;
        this.A217 = 0;
        this.A218 = 0;
        this.A219 = 0;
        this.A220 = 0;
        this.A221 = 0;
        this.A222 = 0;
        this.A223 = 0;
        this.A224 = 0;
        this.A225 = 0;
        this.A226 = 0;
        this.A227 = 0;
        this.A228 = 0;
        this.A229 = 0;
        this.A230 = 0;
        this.A231 = 0;
        this.A903 = 0;
        this.A904 = 0;
        this.A905 = 0;
        this.A902 = 0;
        this.A906 = 0;
        this.A907 = 0;
        this.A901 = 0;
        this.A908 = 0;
        this.A909 = 0;
        this.A910 = 0;
        this.A911 = 0;
        this.A912 = 0;
        this.A913 = 0;
        this.A914 = 0;
        this.A915 = 0;
        this.A916 = 0;
        this.A917 = 0;
        this.A918 = 0;
        this.A919 = 0;
        this.A920 = 0;
        this.A921 = 0;
        this.A922 = 0;
    }

    public JSONObject generateJson(){
        JSONObject obj = new JSONObject();

        GenericHelpers.putIntSafe(obj, A1_KEY, A1);
        GenericHelpers.putIntSafe(obj, A2_KEY, A2);
        GenericHelpers.putIntSafe(obj, A3_KEY, A3);
        GenericHelpers.putIntSafe(obj, A4_KEY, A4);
        GenericHelpers.putIntSafe(obj, A5_KEY, A5);
        GenericHelpers.putIntSafe(obj, A6_KEY, A6);
        GenericHelpers.putIntSafe(obj, A7_KEY, A7);
        GenericHelpers.putIntSafe(obj, A8_KEY, A8);
        GenericHelpers.putIntSafe(obj, A9_KEY, A9);
        GenericHelpers.putIntSafe(obj, A10_KEY, A10);
        GenericHelpers.putIntSafe(obj, A11_KEY, A11);
        GenericHelpers.putIntSafe(obj, A12_KEY, A12);
        GenericHelpers.putIntSafe(obj, A13_KEY, A13);
        GenericHelpers.putIntSafe(obj, A14_KEY, A14);
        GenericHelpers.putIntSafe(obj, A15_KEY, A15);
        GenericHelpers.putIntSafe(obj, A16_KEY, A16);
        GenericHelpers.putIntSafe(obj, A17_KEY, A17);
        GenericHelpers.putIntSafe(obj, A18_KEY, A18);
        GenericHelpers.putIntSafe(obj, A19_KEY, A19);
        GenericHelpers.putIntSafe(obj, A20_KEY, A20);
        GenericHelpers.putIntSafe(obj, A21_KEY, A21);
        GenericHelpers.putIntSafe(obj, A22_KEY, A22);
        GenericHelpers.putIntSafe(obj, A23_KEY, A23);
        GenericHelpers.putIntSafe(obj, A24_KEY, A24);
        GenericHelpers.putIntSafe(obj, A25_KEY, A25);
        GenericHelpers.putIntSafe(obj, A26_KEY, A26);
        GenericHelpers.putIntSafe(obj, A27_KEY, A27);
        GenericHelpers.putIntSafe(obj, A28_KEY, A28);
        GenericHelpers.putIntSafe(obj, A29_KEY, A29);
        GenericHelpers.putIntSafe(obj, A30_KEY, A30);
        GenericHelpers.putIntSafe(obj, A31_KEY, A31);
        GenericHelpers.putIntSafe(obj, A32_KEY, A32);
        GenericHelpers.putIntSafe(obj, A33_KEY, A33);
        GenericHelpers.putIntSafe(obj, A34_KEY, A34);
        GenericHelpers.putIntSafe(obj, A35_KEY, A35);
        GenericHelpers.putIntSafe(obj, A36_KEY, A36);
        GenericHelpers.putIntSafe(obj, A37_KEY, A37);
        GenericHelpers.putIntSafe(obj, A38_KEY, A38);
        GenericHelpers.putIntSafe(obj, A39_KEY, A39);
        GenericHelpers.putIntSafe(obj, A40_KEY, A40);
        GenericHelpers.putIntSafe(obj, A41_KEY, A41);
        GenericHelpers.putIntSafe(obj, A42_KEY, A42);
        GenericHelpers.putIntSafe(obj, A43_KEY, A43);
        GenericHelpers.putIntSafe(obj, A44_KEY, A44);
        GenericHelpers.putIntSafe(obj, A45_KEY, A45);
        GenericHelpers.putIntSafe(obj, A46_KEY, A46);
        GenericHelpers.putIntSafe(obj, A47_KEY, A47);
        GenericHelpers.putIntSafe(obj, A48_KEY, A48);
        GenericHelpers.putIntSafe(obj, A49_KEY, A49);
        GenericHelpers.putIntSafe(obj, A50_KEY, A50);
        GenericHelpers.putIntSafe(obj, A51_KEY, A51);
        GenericHelpers.putIntSafe(obj, A52_KEY, A52);
        GenericHelpers.putIntSafe(obj, A53_KEY, A53);
        GenericHelpers.putIntSafe(obj, A54_KEY, A54);
        GenericHelpers.putIntSafe(obj, A55_KEY, A55);
        GenericHelpers.putIntSafe(obj, A56_KEY, A56);
        GenericHelpers.putIntSafe(obj, A57_KEY, A57);
        GenericHelpers.putIntSafe(obj, A58_KEY, A58);
        GenericHelpers.putIntSafe(obj, A59_KEY, A59);
        GenericHelpers.putIntSafe(obj, A60_KEY, A60);
        GenericHelpers.putIntSafe(obj, A61_KEY, A61);
        GenericHelpers.putIntSafe(obj, A62_KEY, A62);
        GenericHelpers.putIntSafe(obj, A63_KEY, A63);
        GenericHelpers.putIntSafe(obj, A64_KEY, A64);
        GenericHelpers.putIntSafe(obj, A65_KEY, A65);
        GenericHelpers.putIntSafe(obj, A66_KEY, A66);
        GenericHelpers.putIntSafe(obj, A67_KEY, A67);
        GenericHelpers.putIntSafe(obj, A68_KEY, A68);
        GenericHelpers.putIntSafe(obj, A69_KEY, A69);
        GenericHelpers.putIntSafe(obj, A70_KEY, A70);
        GenericHelpers.putIntSafe(obj, A71_KEY, A71);
        GenericHelpers.putIntSafe(obj, A72_KEY, A72);
        GenericHelpers.putIntSafe(obj, A73_KEY, A73);
        GenericHelpers.putIntSafe(obj, A74_KEY, A74);
        GenericHelpers.putIntSafe(obj, A75_KEY, A75);
        GenericHelpers.putIntSafe(obj, A76_KEY, A76);
        GenericHelpers.putIntSafe(obj, A77_KEY, A77);
        GenericHelpers.putIntSafe(obj, A78_KEY, A78);
        GenericHelpers.putIntSafe(obj, A79_KEY, A79);
        GenericHelpers.putIntSafe(obj, A80_KEY, A80);
        GenericHelpers.putIntSafe(obj, A81_KEY, A81);
        GenericHelpers.putIntSafe(obj, A82_KEY, A82);
        GenericHelpers.putIntSafe(obj, A83_KEY, A83);
        GenericHelpers.putIntSafe(obj, A84_KEY, A84);
        GenericHelpers.putIntSafe(obj, A85_KEY, A85);
        GenericHelpers.putIntSafe(obj, A86_KEY, A86);
        GenericHelpers.putIntSafe(obj, A87_KEY, A87);
        GenericHelpers.putIntSafe(obj, A88_KEY, A88);
        GenericHelpers.putIntSafe(obj, A89_KEY, A89);
        GenericHelpers.putIntSafe(obj, A90_KEY, A90);
        GenericHelpers.putIntSafe(obj, A91_KEY, A91);
        GenericHelpers.putIntSafe(obj, A92_KEY, A92);
        GenericHelpers.putIntSafe(obj, A93_KEY, A93);
        GenericHelpers.putIntSafe(obj, A94_KEY, A94);
        GenericHelpers.putIntSafe(obj, A95_KEY, A95);
        GenericHelpers.putIntSafe(obj, A96_KEY, A96);
        GenericHelpers.putIntSafe(obj, A97_KEY, A97);
        GenericHelpers.putIntSafe(obj, A98_KEY, A98);
        GenericHelpers.putIntSafe(obj, A99_KEY, A99);
        GenericHelpers.putIntSafe(obj, A100_KEY, A100);
        GenericHelpers.putIntSafe(obj, A101_KEY, A101);
        GenericHelpers.putIntSafe(obj, A102_KEY, A102);
        GenericHelpers.putIntSafe(obj, A103_KEY, A103);
        GenericHelpers.putIntSafe(obj, A104_KEY, A104);
        GenericHelpers.putIntSafe(obj, A105_KEY, A105);
        GenericHelpers.putIntSafe(obj, A106_KEY, A106);
        GenericHelpers.putIntSafe(obj, A107_KEY, A107);
        GenericHelpers.putIntSafe(obj, A108_KEY, A108);
        GenericHelpers.putIntSafe(obj, A109_KEY, A109);
        GenericHelpers.putIntSafe(obj, A110_KEY, A110);
        GenericHelpers.putIntSafe(obj, A111_KEY, A111);
        GenericHelpers.putIntSafe(obj, A112_KEY, A112);
        GenericHelpers.putIntSafe(obj, A113_KEY, A113);
        GenericHelpers.putIntSafe(obj, A114_KEY, A114);
        GenericHelpers.putIntSafe(obj, A115_KEY, A115);
        GenericHelpers.putIntSafe(obj, A116_KEY, A116);
        GenericHelpers.putIntSafe(obj, A117_KEY, A117);
        GenericHelpers.putIntSafe(obj, A118_KEY, A118);
        GenericHelpers.putIntSafe(obj, A119_KEY, A119);
        GenericHelpers.putIntSafe(obj, A120_KEY, A120);
        GenericHelpers.putIntSafe(obj, A121_KEY, A121);
        GenericHelpers.putIntSafe(obj, A122_KEY, A122);
        GenericHelpers.putIntSafe(obj, A123_KEY, A123);
        GenericHelpers.putIntSafe(obj, A124_KEY, A124);
        GenericHelpers.putIntSafe(obj, A125_KEY, A125);
        GenericHelpers.putIntSafe(obj, A126_KEY, A126);
        GenericHelpers.putIntSafe(obj, A127_KEY, A127);
        GenericHelpers.putIntSafe(obj, A128_KEY, A128);
        GenericHelpers.putIntSafe(obj, A129_KEY, A129);
        GenericHelpers.putIntSafe(obj, A130_KEY, A130);
        GenericHelpers.putIntSafe(obj, A131_KEY, A131);
        GenericHelpers.putIntSafe(obj, A132_KEY, A132);
        GenericHelpers.putIntSafe(obj, A133_KEY, A133);
        GenericHelpers.putIntSafe(obj, A134_KEY, A134);
        GenericHelpers.putIntSafe(obj, A135_KEY, A135);
        GenericHelpers.putIntSafe(obj, A136_KEY, A136);
        GenericHelpers.putIntSafe(obj, A137_KEY, A137);
        GenericHelpers.putIntSafe(obj, A138_KEY, A138);
        GenericHelpers.putIntSafe(obj, A139_KEY, A139);
        GenericHelpers.putIntSafe(obj, A140_KEY, A140);
        GenericHelpers.putIntSafe(obj, A141_KEY, A141);
        GenericHelpers.putIntSafe(obj, A142_KEY, A142);
        GenericHelpers.putIntSafe(obj, A143_KEY, A143);
        GenericHelpers.putIntSafe(obj, A144_KEY, A144);
        GenericHelpers.putIntSafe(obj, A145_KEY, A145);
        GenericHelpers.putIntSafe(obj, A146_KEY, A146);
        GenericHelpers.putIntSafe(obj, A147_KEY, A147);
        GenericHelpers.putIntSafe(obj, A148_KEY, A148);
        GenericHelpers.putIntSafe(obj, A149_KEY, A149);
        GenericHelpers.putIntSafe(obj, A150_KEY, A150);
        GenericHelpers.putIntSafe(obj, A151_KEY, A151);
        GenericHelpers.putIntSafe(obj, A152_KEY, A152);
        GenericHelpers.putIntSafe(obj, A153_KEY, A153);
        GenericHelpers.putIntSafe(obj, A154_KEY, A154);
        GenericHelpers.putIntSafe(obj, A155_KEY, A155);
        GenericHelpers.putIntSafe(obj, A156_KEY, A156);
        GenericHelpers.putIntSafe(obj, A157_KEY, A157);
        GenericHelpers.putIntSafe(obj, A158_KEY, A158);
        GenericHelpers.putIntSafe(obj, A159_KEY, A159);
        GenericHelpers.putIntSafe(obj, A160_KEY, A160);
        GenericHelpers.putIntSafe(obj, A161_KEY, A161);
        GenericHelpers.putIntSafe(obj, A162_KEY, A162);
        GenericHelpers.putIntSafe(obj, A163_KEY, A163);
        GenericHelpers.putIntSafe(obj, A164_KEY, A164);
        GenericHelpers.putIntSafe(obj, A165_KEY, A165);
        GenericHelpers.putIntSafe(obj, A166_KEY, A166);
        GenericHelpers.putIntSafe(obj, A167_KEY, A167);
        GenericHelpers.putIntSafe(obj, A168_KEY, A168);
        GenericHelpers.putIntSafe(obj, A169_KEY, A169);
        GenericHelpers.putIntSafe(obj, A170_KEY, A170);
        GenericHelpers.putIntSafe(obj, A171_KEY, A171);
        GenericHelpers.putIntSafe(obj, A172_KEY, A172);
        GenericHelpers.putIntSafe(obj, A173_KEY, A173);
        GenericHelpers.putIntSafe(obj, A174_KEY, A174);
        GenericHelpers.putIntSafe(obj, A175_KEY, A175);
        GenericHelpers.putIntSafe(obj, A176_KEY, A176);
        GenericHelpers.putIntSafe(obj, A177_KEY, A177);
        GenericHelpers.putIntSafe(obj, A178_KEY, A178);
        GenericHelpers.putIntSafe(obj, A179_KEY, A179);
        GenericHelpers.putIntSafe(obj, A180_KEY, A180);
        GenericHelpers.putIntSafe(obj, A181_KEY, A181);
        GenericHelpers.putIntSafe(obj, A182_KEY, A182);
        GenericHelpers.putIntSafe(obj, A183_KEY, A183);
        GenericHelpers.putIntSafe(obj, A184_KEY, A184);
        GenericHelpers.putIntSafe(obj, A185_KEY, A185);
        GenericHelpers.putIntSafe(obj, A186_KEY, A186);
        GenericHelpers.putIntSafe(obj, A187_KEY, A187);
        GenericHelpers.putIntSafe(obj, A188_KEY, A188);
        GenericHelpers.putIntSafe(obj, A189_KEY, A189);
        GenericHelpers.putIntSafe(obj, A190_KEY, A190);
        GenericHelpers.putIntSafe(obj, A191_KEY, A191);
        GenericHelpers.putIntSafe(obj, A192_KEY, A192);
        GenericHelpers.putIntSafe(obj, A193_KEY, A193);
        GenericHelpers.putIntSafe(obj, A194_KEY, A194);
        GenericHelpers.putIntSafe(obj, A195_KEY, A195);
        GenericHelpers.putIntSafe(obj, A196_KEY, A196);
        GenericHelpers.putIntSafe(obj, A197_KEY, A197);
        GenericHelpers.putIntSafe(obj, A198_KEY, A198);
        GenericHelpers.putIntSafe(obj, A199_KEY, A199);
        GenericHelpers.putIntSafe(obj, A200_KEY, A200);
        GenericHelpers.putIntSafe(obj, A201_KEY, A201);
        GenericHelpers.putIntSafe(obj, A202_KEY, A202);
        GenericHelpers.putIntSafe(obj, A203_KEY, A203);
        GenericHelpers.putIntSafe(obj, A204_KEY, A204);
        GenericHelpers.putIntSafe(obj, A205_KEY, A205);
        GenericHelpers.putIntSafe(obj, A206_KEY, A206);
        GenericHelpers.putIntSafe(obj, A207_KEY, A207);
        GenericHelpers.putIntSafe(obj, A208_KEY, A208);
        GenericHelpers.putIntSafe(obj, A209_KEY, A209);
        GenericHelpers.putIntSafe(obj, A210_KEY, A210);
        GenericHelpers.putIntSafe(obj, A211_KEY, A211);
        GenericHelpers.putIntSafe(obj, A212_KEY, A212);
        GenericHelpers.putIntSafe(obj, A213_KEY, A213);
        GenericHelpers.putIntSafe(obj, A214_KEY, A214);
        GenericHelpers.putIntSafe(obj, A215_KEY, A215);
        GenericHelpers.putIntSafe(obj, A216_KEY, A216);
        GenericHelpers.putIntSafe(obj, A217_KEY, A217);
        GenericHelpers.putIntSafe(obj, A218_KEY, A218);
        GenericHelpers.putIntSafe(obj, A219_KEY, A219);
        GenericHelpers.putIntSafe(obj, A220_KEY, A220);
        GenericHelpers.putIntSafe(obj, A221_KEY, A221);
        GenericHelpers.putIntSafe(obj, A222_KEY, A222);
        GenericHelpers.putIntSafe(obj, A223_KEY, A223);
        GenericHelpers.putIntSafe(obj, A224_KEY, A224);
        GenericHelpers.putIntSafe(obj, A225_KEY, A225);
        GenericHelpers.putIntSafe(obj, A226_KEY, A226);
        GenericHelpers.putIntSafe(obj, A227_KEY, A227);
        GenericHelpers.putIntSafe(obj, A228_KEY, A228);
        GenericHelpers.putIntSafe(obj, A229_KEY, A229);
        GenericHelpers.putIntSafe(obj, A230_KEY, A230);
        GenericHelpers.putIntSafe(obj, A231_KEY, A231);
        GenericHelpers.putIntSafe(obj, A903_KEY, A903);
        GenericHelpers.putIntSafe(obj, A904_KEY, A904);
        GenericHelpers.putIntSafe(obj, A905_KEY, A905);
        GenericHelpers.putIntSafe(obj, A902_KEY, A902);
        GenericHelpers.putIntSafe(obj, A906_KEY, A906);
        GenericHelpers.putIntSafe(obj, A907_KEY, A907);
        GenericHelpers.putIntSafe(obj, A901_KEY, A901);
        GenericHelpers.putIntSafe(obj, A908_KEY, A908);
        GenericHelpers.putIntSafe(obj, A909_KEY, A909);
        GenericHelpers.putIntSafe(obj, A910_KEY, A910);
        GenericHelpers.putIntSafe(obj, A911_KEY, A911);
        GenericHelpers.putIntSafe(obj, A912_KEY, A912);
        GenericHelpers.putIntSafe(obj, A913_KEY, A913);
        GenericHelpers.putIntSafe(obj, A914_KEY, A914);
        GenericHelpers.putIntSafe(obj, A915_KEY, A915);
        GenericHelpers.putIntSafe(obj, A916_KEY, A916);
        GenericHelpers.putIntSafe(obj, A917_KEY, A917);
        GenericHelpers.putIntSafe(obj, A918_KEY, A918);
        GenericHelpers.putIntSafe(obj, A919_KEY, A919);
        GenericHelpers.putIntSafe(obj, A920_KEY, A920);
        GenericHelpers.putIntSafe(obj, A921_KEY, A921);
        GenericHelpers.putIntSafe(obj, A922_KEY, A922);

        return obj;
    }
}
