package com.titansmasher.taptitansoptimizer.Model.RawSave.ArtifactClasses;

import com.titansmasher.taptitansoptimizer.Helpers.GenericHelpers;
import com.titansmasher.taptitansoptimizer.Model.RawSave.Abstracts.ArtifactData;

import org.json.JSONObject;

/**
 * Created by Danny on 22/10/2016.
 */

public class ArtifactRelics extends ArtifactData<Integer> {
    public ArtifactRelics(JSONObject obj) {
        if (obj == null) {
            populateFromNull();
            return;
        }
        this.Artifact1 =  GenericHelpers.getIntSafe(obj, ARTIFACT1_KEY);
        this.Artifact2 =  GenericHelpers.getIntSafe(obj, ARTIFACT2_KEY);
        this.Artifact3 =  GenericHelpers.getIntSafe(obj, ARTIFACT3_KEY);
        this.Artifact4 =  GenericHelpers.getIntSafe(obj, ARTIFACT4_KEY);
        this.Artifact5 =  GenericHelpers.getIntSafe(obj, ARTIFACT5_KEY);
        this.Artifact6 =  GenericHelpers.getIntSafe(obj, ARTIFACT6_KEY);
        this.Artifact7 =  GenericHelpers.getIntSafe(obj, ARTIFACT7_KEY);
        this.Artifact8 =  GenericHelpers.getIntSafe(obj, ARTIFACT8_KEY);
        this.Artifact9 =  GenericHelpers.getIntSafe(obj, ARTIFACT9_KEY);
        this.Artifact10 = GenericHelpers.getIntSafe(obj, ARTIFACT10_KEY);
        this.Artifact11 = GenericHelpers.getIntSafe(obj, ARTIFACT11_KEY);
        this.Artifact12 = GenericHelpers.getIntSafe(obj, ARTIFACT12_KEY);
        this.Artifact13 = GenericHelpers.getIntSafe(obj, ARTIFACT13_KEY);
        this.Artifact14 = GenericHelpers.getIntSafe(obj, ARTIFACT14_KEY);
        this.Artifact15 = GenericHelpers.getIntSafe(obj, ARTIFACT15_KEY);
        this.Artifact16 = GenericHelpers.getIntSafe(obj, ARTIFACT16_KEY);
        this.Artifact17 = GenericHelpers.getIntSafe(obj, ARTIFACT17_KEY);
        this.Artifact18 = GenericHelpers.getIntSafe(obj, ARTIFACT18_KEY);
        this.Artifact19 = GenericHelpers.getIntSafe(obj, ARTIFACT19_KEY);
        this.Artifact20 = GenericHelpers.getIntSafe(obj, ARTIFACT20_KEY);
        this.Artifact21 = GenericHelpers.getIntSafe(obj, ARTIFACT21_KEY);
        this.Artifact22 = GenericHelpers.getIntSafe(obj, ARTIFACT22_KEY);
        this.Artifact23 = GenericHelpers.getIntSafe(obj, ARTIFACT23_KEY);
        this.Artifact24 = GenericHelpers.getIntSafe(obj, ARTIFACT24_KEY);
        this.Artifact25 = GenericHelpers.getIntSafe(obj, ARTIFACT25_KEY);
        this.Artifact26 = GenericHelpers.getIntSafe(obj, ARTIFACT26_KEY);
        this.Artifact27 = GenericHelpers.getIntSafe(obj, ARTIFACT27_KEY);
        this.Artifact28 = GenericHelpers.getIntSafe(obj, ARTIFACT28_KEY);
        this.Artifact29 = GenericHelpers.getIntSafe(obj, ARTIFACT29_KEY);
        this.Artifact30 = GenericHelpers.getIntSafe(obj, ARTIFACT30_KEY);
        this.Artifact31 = GenericHelpers.getIntSafe(obj, ARTIFACT31_KEY);
        this.Artifact32 = GenericHelpers.getIntSafe(obj, ARTIFACT32_KEY);
        this.Artifact33 = GenericHelpers.getIntSafe(obj, ARTIFACT33_KEY);
        this.Artifact34 = GenericHelpers.getIntSafe(obj, ARTIFACT34_KEY);
        this.Artifact35 = GenericHelpers.getIntSafe(obj, ARTIFACT35_KEY);
        this.Artifact36 = GenericHelpers.getIntSafe(obj, ARTIFACT36_KEY);
        this.Artifact37 = GenericHelpers.getIntSafe(obj, ARTIFACT37_KEY);
        this.Artifact38 = GenericHelpers.getIntSafe(obj, ARTIFACT38_KEY);
        this.Artifact39 = GenericHelpers.getIntSafe(obj, ARTIFACT39_KEY);
        this.Artifact40 = GenericHelpers.getIntSafe(obj, ARTIFACT40_KEY);
        this.Artifact41 = GenericHelpers.getIntSafe(obj, ARTIFACT41_KEY);
        this.Artifact42 = GenericHelpers.getIntSafe(obj, ARTIFACT42_KEY);
        this.Artifact43 = GenericHelpers.getIntSafe(obj, ARTIFACT43_KEY);
        this.Artifact44 = GenericHelpers.getIntSafe(obj, ARTIFACT44_KEY);
        this.Artifact45 = GenericHelpers.getIntSafe(obj, ARTIFACT45_KEY);
        this.Artifact46 = GenericHelpers.getIntSafe(obj, ARTIFACT46_KEY);
        this.Artifact47 = GenericHelpers.getIntSafe(obj, ARTIFACT47_KEY);
        this.Artifact48 = GenericHelpers.getIntSafe(obj, ARTIFACT48_KEY);
        this.Artifact49 = GenericHelpers.getIntSafe(obj, ARTIFACT49_KEY);
        this.Artifact50 = GenericHelpers.getIntSafe(obj, ARTIFACT50_KEY);
        this.Artifact51 = GenericHelpers.getIntSafe(obj, ARTIFACT51_KEY);
        this.Artifact52 = GenericHelpers.getIntSafe(obj, ARTIFACT52_KEY);
        this.Artifact53 = GenericHelpers.getIntSafe(obj, ARTIFACT53_KEY);
        this.Artifact54 = GenericHelpers.getIntSafe(obj, ARTIFACT54_KEY);
        this.Artifact55 = GenericHelpers.getIntSafe(obj, ARTIFACT55_KEY);
        this.Artifact56 = GenericHelpers.getIntSafe(obj, ARTIFACT56_KEY);
        this.Artifact57 = GenericHelpers.getIntSafe(obj, ARTIFACT57_KEY);
        this.Artifact58 = GenericHelpers.getIntSafe(obj, ARTIFACT58_KEY);
        this.Artifact59 = GenericHelpers.getIntSafe(obj, ARTIFACT59_KEY);
        this.Artifact60 = GenericHelpers.getIntSafe(obj, ARTIFACT60_KEY);
        this.Artifact61 = GenericHelpers.getIntSafe(obj, ARTIFACT61_KEY);
        this.Artifact62 = GenericHelpers.getIntSafe(obj, ARTIFACT62_KEY);
        this.Artifact63 = GenericHelpers.getIntSafe(obj, ARTIFACT63_KEY);
        this.Artifact64 = GenericHelpers.getIntSafe(obj, ARTIFACT64_KEY);
        this.Artifact65 = GenericHelpers.getIntSafe(obj, ARTIFACT65_KEY);
        this.Artifact66 = GenericHelpers.getIntSafe(obj, ARTIFACT66_KEY);
        this.Artifact67 = GenericHelpers.getIntSafe(obj, ARTIFACT67_KEY);
        this.Artifact68 = GenericHelpers.getIntSafe(obj, ARTIFACT68_KEY);
        this.Artifact69 = GenericHelpers.getIntSafe(obj, ARTIFACT69_KEY);
        this.Artifact70 = GenericHelpers.getIntSafe(obj, ARTIFACT70_KEY);
    }

    private void populateFromNull() {
        this.Artifact1 = 0;
        this.Artifact2 = 0;
        this.Artifact3 = 0;
        this.Artifact4 = 0;
        this.Artifact5 = 0;
        this.Artifact6 = 0;
        this.Artifact7 = 0;
        this.Artifact8 = 0;
        this.Artifact9 = 0;
        this.Artifact10 = 0;
        this.Artifact11 = 0;
        this.Artifact12 = 0;
        this.Artifact13 = 0;
        this.Artifact14 = 0;
        this.Artifact15 = 0;
        this.Artifact16 = 0;
        this.Artifact17 = 0;
        this.Artifact18 = 0;
        this.Artifact19 = 0;
        this.Artifact20 = 0;
        this.Artifact21 = 0;
        this.Artifact22 = 0;
        this.Artifact23 = 0;
        this.Artifact24 = 0;
        this.Artifact25 = 0;
        this.Artifact26 = 0;
        this.Artifact27 = 0;
        this.Artifact28 = 0;
        this.Artifact29 = 0;
        this.Artifact30 = 0;
        this.Artifact31 = 0;
        this.Artifact32 = 0;
        this.Artifact33 = 0;
        this.Artifact34 = 0;
        this.Artifact35 = 0;
        this.Artifact36 = 0;
        this.Artifact37 = 0;
        this.Artifact38 = 0;
        this.Artifact39 = 0;
        this.Artifact40 = 0;
        this.Artifact41 = 0;
        this.Artifact42 = 0;
        this.Artifact43 = 0;
        this.Artifact44 = 0;
        this.Artifact45 = 0;
        this.Artifact46 = 0;
        this.Artifact47 = 0;
        this.Artifact48 = 0;
        this.Artifact49 = 0;
        this.Artifact50 = 0;
        this.Artifact51 = 0;
        this.Artifact52 = 0;
        this.Artifact53 = 0;
        this.Artifact54 = 0;
        this.Artifact55 = 0;
        this.Artifact56 = 0;
        this.Artifact57 = 0;
        this.Artifact58 = 0;
        this.Artifact59 = 0;
        this.Artifact60 = 0;
        this.Artifact61 = 0;
        this.Artifact62 = 0;
        this.Artifact63 = 0;
        this.Artifact64 = 0;
        this.Artifact65 = 0;
        this.Artifact66 = 0;
        this.Artifact67 = 0;
        this.Artifact68 = 0;
        this.Artifact69 = 0;
        this.Artifact70 = 0;
    }

    public JSONObject generateJson(){
        JSONObject obj = new JSONObject();

        GenericHelpers.putIntSafe(obj, ARTIFACT1_KEY, Artifact1);
        GenericHelpers.putIntSafe(obj, ARTIFACT2_KEY, Artifact2);
        GenericHelpers.putIntSafe(obj, ARTIFACT3_KEY, Artifact3);
        GenericHelpers.putIntSafe(obj, ARTIFACT4_KEY, Artifact4);
        GenericHelpers.putIntSafe(obj, ARTIFACT5_KEY, Artifact5);
        GenericHelpers.putIntSafe(obj, ARTIFACT6_KEY, Artifact6);
        GenericHelpers.putIntSafe(obj, ARTIFACT7_KEY, Artifact7);
        GenericHelpers.putIntSafe(obj, ARTIFACT8_KEY, Artifact8);
        GenericHelpers.putIntSafe(obj, ARTIFACT9_KEY, Artifact9);
        GenericHelpers.putIntSafe(obj, ARTIFACT10_KEY, Artifact10);
        GenericHelpers.putIntSafe(obj, ARTIFACT11_KEY, Artifact11);
        GenericHelpers.putIntSafe(obj, ARTIFACT12_KEY, Artifact12);
        GenericHelpers.putIntSafe(obj, ARTIFACT13_KEY, Artifact13);
        GenericHelpers.putIntSafe(obj, ARTIFACT14_KEY, Artifact14);
        GenericHelpers.putIntSafe(obj, ARTIFACT15_KEY, Artifact15);
        GenericHelpers.putIntSafe(obj, ARTIFACT16_KEY, Artifact16);
        GenericHelpers.putIntSafe(obj, ARTIFACT17_KEY, Artifact17);
        GenericHelpers.putIntSafe(obj, ARTIFACT18_KEY, Artifact18);
        GenericHelpers.putIntSafe(obj, ARTIFACT19_KEY, Artifact19);
        GenericHelpers.putIntSafe(obj, ARTIFACT20_KEY, Artifact20);
        GenericHelpers.putIntSafe(obj, ARTIFACT21_KEY, Artifact21);
        GenericHelpers.putIntSafe(obj, ARTIFACT22_KEY, Artifact22);
        GenericHelpers.putIntSafe(obj, ARTIFACT23_KEY, Artifact23);
        GenericHelpers.putIntSafe(obj, ARTIFACT24_KEY, Artifact24);
        GenericHelpers.putIntSafe(obj, ARTIFACT25_KEY, Artifact25);
        GenericHelpers.putIntSafe(obj, ARTIFACT26_KEY, Artifact26);
        GenericHelpers.putIntSafe(obj, ARTIFACT27_KEY, Artifact27);
        GenericHelpers.putIntSafe(obj, ARTIFACT28_KEY, Artifact28);
        GenericHelpers.putIntSafe(obj, ARTIFACT29_KEY, Artifact29);
        GenericHelpers.putIntSafe(obj, ARTIFACT30_KEY, Artifact30);
        GenericHelpers.putIntSafe(obj, ARTIFACT31_KEY, Artifact31);
        GenericHelpers.putIntSafe(obj, ARTIFACT32_KEY, Artifact32);
        GenericHelpers.putIntSafe(obj, ARTIFACT33_KEY, Artifact33);
        GenericHelpers.putIntSafe(obj, ARTIFACT34_KEY, Artifact34);
        GenericHelpers.putIntSafe(obj, ARTIFACT35_KEY, Artifact35);
        GenericHelpers.putIntSafe(obj, ARTIFACT36_KEY, Artifact36);
        GenericHelpers.putIntSafe(obj, ARTIFACT37_KEY, Artifact37);
        GenericHelpers.putIntSafe(obj, ARTIFACT38_KEY, Artifact38);
        GenericHelpers.putIntSafe(obj, ARTIFACT39_KEY, Artifact39);
        GenericHelpers.putIntSafe(obj, ARTIFACT40_KEY, Artifact40);
        GenericHelpers.putIntSafe(obj, ARTIFACT41_KEY, Artifact41);
        GenericHelpers.putIntSafe(obj, ARTIFACT42_KEY, Artifact42);
        GenericHelpers.putIntSafe(obj, ARTIFACT43_KEY, Artifact43);
        GenericHelpers.putIntSafe(obj, ARTIFACT44_KEY, Artifact44);
        GenericHelpers.putIntSafe(obj, ARTIFACT45_KEY, Artifact45);
        GenericHelpers.putIntSafe(obj, ARTIFACT46_KEY, Artifact46);
        GenericHelpers.putIntSafe(obj, ARTIFACT47_KEY, Artifact47);
        GenericHelpers.putIntSafe(obj, ARTIFACT48_KEY, Artifact48);
        GenericHelpers.putIntSafe(obj, ARTIFACT49_KEY, Artifact49);
        GenericHelpers.putIntSafe(obj, ARTIFACT50_KEY, Artifact50);
        GenericHelpers.putIntSafe(obj, ARTIFACT51_KEY, Artifact51);
        GenericHelpers.putIntSafe(obj, ARTIFACT52_KEY, Artifact52);
        GenericHelpers.putIntSafe(obj, ARTIFACT53_KEY, Artifact53);
        GenericHelpers.putIntSafe(obj, ARTIFACT54_KEY, Artifact54);
        GenericHelpers.putIntSafe(obj, ARTIFACT55_KEY, Artifact55);
        GenericHelpers.putIntSafe(obj, ARTIFACT56_KEY, Artifact56);
        GenericHelpers.putIntSafe(obj, ARTIFACT57_KEY, Artifact57);
        GenericHelpers.putIntSafe(obj, ARTIFACT58_KEY, Artifact58);
        GenericHelpers.putIntSafe(obj, ARTIFACT59_KEY, Artifact59);
        GenericHelpers.putIntSafe(obj, ARTIFACT60_KEY, Artifact60);
        GenericHelpers.putIntSafe(obj, ARTIFACT61_KEY, Artifact61);
        GenericHelpers.putIntSafe(obj, ARTIFACT62_KEY, Artifact62);
        GenericHelpers.putIntSafe(obj, ARTIFACT63_KEY, Artifact63);
        GenericHelpers.putIntSafe(obj, ARTIFACT64_KEY, Artifact64);
        GenericHelpers.putIntSafe(obj, ARTIFACT65_KEY, Artifact65);
        GenericHelpers.putIntSafe(obj, ARTIFACT66_KEY, Artifact66);
        GenericHelpers.putIntSafe(obj, ARTIFACT67_KEY, Artifact67);
        GenericHelpers.putIntSafe(obj, ARTIFACT68_KEY, Artifact68);
        GenericHelpers.putIntSafe(obj, ARTIFACT69_KEY, Artifact69);
        GenericHelpers.putIntSafe(obj, ARTIFACT70_KEY, Artifact70);

        return obj;
    }
}
