package com.titansmasher.taptitansoptimizer.Model.Enums;

/**
 * Created by Danny on 31/10/2016.
 */

public enum Page {
    STATS_ACCOUNT,
    STATS_WORLD,
    STATS_ARTIFACT,
    STATS_HERO,

    OPTIMISER_SETTINGS,
    OPTIMISER_CUSTOMHEROLEVELS,
    OPTIMISER_DMG,
    OPTIMISER_GOLD,
    OPTIMISER_TDMG,
    OPTIMISER_DMGE,

    SEQUENCER_ARTIFACT,
    SEQUENCER_WEAPON,
    SEQUENCER_ARTIFACT_PRIORITIES,
    SEQUENCER_ARTIFACT_OPTIMISER,

    SAVE_MANAGE,
    SAVE_EDITARTIFACT,
    SAVE_EDITCUSTOMISATION,
    SAVE_EDITGENERAL,

    FAQABOUT_ABOUT,
    FAQABOUT_FAQ,
    FAQABOUT_CREDITS

}
