package com.titansmasher.taptitansoptimizer.Model.RawSave;

import com.titansmasher.taptitansoptimizer.Helpers.GenericHelpers;
import com.titansmasher.taptitansoptimizer.Model.RawSave.AbilityClasses.AbilitySave;
import com.titansmasher.taptitansoptimizer.Model.RawSave.ArtifactClasses.ArtifactLevels;
import com.titansmasher.taptitansoptimizer.Model.RawSave.ArtifactClasses.ArtifactRelics;
import com.titansmasher.taptitansoptimizer.Model.RawSave.HeroClasses.HeroSave;
import com.titansmasher.taptitansoptimizer.Model.RawSave.TrophyClasses.TrophyProgressSave;

import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.UUID;

/**
 * Created by Danny on 19/10/2016.
 */

public class PlayerInfoSave {

    public UUID playerId;
    public String friendCode;
    public int cleanMasterDiamonds;
    public int playerLevel;
    public int playerLevelGirl;
    public Date lastActiveTime;
    public Date lastActiveTimeGirl;
    public double playerGold;
    public double playerGoldGirl;
    public int playerRelics;
    public int playerRelicsGirl;
    public int playerDiamonds;
    public boolean hasOfflineGold;
    public boolean skipOfflineGold;
    public int currentStage;
    public int currentStageGirl;
    public int unlockedStage;
    public int unlockedStageGirl;
    public int killsInWave;
    public int killsInWaveGirl;
    public boolean beenToLatestStage;
    public boolean beenToLatestStageGirl;
    public boolean signedIntoSocial;
    public boolean shouldAskToSignInSocial;
    public String socialId;
    public ArtifactLevels artifactLevels;
    public HeroSave heroSave;
    public AbilitySave abilitySave;
    public ArtifactRelics artifactRelicsSpent;
    public boolean artifactRelicsSpentFixed;
    public int nextArtifactSeed;
    public int nextArtifactSeedGirl;
    public TrophyProgressSave trophyProgress;
    public TrophyProgressSave trophyProgressGirl;
    public PowerUpInventory powerUpInventory;
    public boolean cheater;
    public String cheaterReason;
    public int syncCount;
    public double playTimeSinceLastSync;
    public double playTimeSinceLastSyncGirl;
    public double originalTimeOffset;
    public double goldLostToPrestige;
    public double goldLostToPrestigeGirl;
    public double dpsLostToPrestige;
    public double dpsLostToPrestigeGirl;
    public Date lastPrestige;
    public Date lastPrestigeGirl;
    public double uncollectedGold;
    public double uncollectedGoldGirl;
    public int cheatCount;
    public int world;
    public int iapPurchaseCount;
    public double iapSpendingInUSD;
    public int iapApprovedByAppleGoogle;
    public RewardedIAPs allRewardedIAPs;
    public int rewardedCustomerServiceDiamond;
    public int rewardedCustomerServiceRelics;
    public TutorialProgress tutorialProgress;
    public int dungeonsCompleted;
    public int dungeonStage;
    public Date lastDungeonTime;
    public Date lastCompletedDungeonTime;
    public Tournament tournament;
    public Date doubleFairyTime;
    public Inbox readInboxMessages;
    public int tt_language; // language is a built in variable *somewhere*
    public boolean hideTournamentPanel;
    public int gameRating;
    public boolean isLinkedToFacebook;
    public PlayerCustomizations unlockedPlayerCustomizations;
    public PlayerCustomizations currentPlayerCustomizations;
    public Friends friendsModel;
    public String facebookId;
    public int dailyClickMinValue;
    public int music;
    public int sound;
    public boolean pushNotifications;
    public boolean calculatorMode;
    public boolean optionsAutoAdvance;
    public boolean optionsAutoAdvanceGirl;
    public boolean optionsAutoAdvanceBoy;
    public boolean hasRatedGame;
    public boolean seenOfflineGoldPanel;
    public boolean likedFacebook;
    public boolean followedTwitter;
    public String playerName;
    public String playerNameGirl;
    public boolean optionsFairyVideo;
    public boolean optionsMultiplayerEnabled;
    public int optionsPerformance;
    public boolean hasOpenedFriendsPanel;
    public String backupIAPProductIdentifier;
    public String backupIAPBase64EncodedTransactionReceipt;
    public String lastSavedVersion;
    public boolean firstPurchaseMsgShown;
    public Date lastCloudSaveTime;
    public Date lastClickPeriod;
    public boolean hasCloudSaveEverSynced;
    public boolean canDoSeason2;
    public boolean drunkenHammerRewardeReceived;
    public boolean isDeveloper;
    public String firstVersionInstalled;
    public String oniixTransferKey;
    public String superPrestige;
    public int activeTime;

    private String PLAYERID_KEY = "playerID";
    private String FRIENDCODE_KEY = "friendCode";
    private String CLEANMASTERDIAMONDS_KEY = "cleanMasterDiamonds";
    private String PLAYERLEVEL_KEY = "playerLevel";
    private String PLAYERLEVELGIRL_KEY = "playerLevelGirl";
    private String LASTACTIVETIME_KEY = "lastActiveTime";
    private String LASTACTIVETIMEGIRL_KEY = "lastActiveTimeGirl";
    private String PLAYERGOLD_KEY = "playerGold";
    private String PLAYERGOLDGIRL_KEY = "playerGoldGirl";
    private String PLAYERRELICS_KEY = "playerRelics";
    private String PLAYERRELICSGIRL_KEY = "playerRelicsGirl";
    private String PLAYERDIAMONDS_KEY = "playerDiamonds";
    private String HASOFFLINEGOLD_KEY = "hasOfflineGold";
    private String SKIPOFFLINEGOLD_KEY = "skipOfflineGold";
    private String CURRENTSTAGE_KEY = "currentStage";
    private String CURRENTSTAGEGIRL_KEY = "currentStageGirl";
    private String UNLOCKEDSTAGE_KEY = "unlockedStage";
    private String UNLOCKEDSTAGEGIRL_KEY = "unlockedStageGirl";
    private String KILLSINWAVE_KEY = "killsInWave";
    private String KILLSINWAVEGIRL_KEY = "killsInWaveGirl";
    private String BEENTOLATESTSTAGE_KEY = "beenToLatestStage";
    private String BEENTOLATESTSTAGEGIRL_KEY = "beenToLatestStageGirl";
    private String SIGNEDINTOSOCIAL_KEY = "signedIntoSocial";
    private String SHOULDASKTOSIGNINSOCIAL_KEY = "shouldAskToSignInSocial";
    private String SOCIALID_KEY = "socialId";
    private String ARTIFACTLEVELS_KEY = "artifactLevels";
    private String HEROSAVE_KEY = "heroSave";
    private String ABILITYSAVE_KEY = "skillSave";
    private String ARTIFACTRELICSSPENT_KEY = "artifactRelicsSpent";
    private String ARTIFACTRELICSSPENTFIXED_KEY = "artifactRelicsSpentFixed";
    private String NEXTARTIFACTSEED_KEY = "nextArtifactSeed";
    private String NEXTARTIFACTSEEDGIRL_KEY = "nextArtifactSeedGirl";
    private String TROPHYPROGRESS_KEY = "trophyProgress";
    private String TROPHYPROGRESSGIRL_KEY = "trophyProgressGirl";
    private String POWERUPINVENTORY_KEY = "powerUpInventory";
    private String CHEATER_KEY = "cheater";
    private String CHEATERREASON_KEY = "cheaterReason";
    private String SYNCCOUNT_KEY = "syncCount";
    private String PLAYTIMESINCELASTSYNC_KEY = "playTimeSinceLastSync";
    private String PLAYTIMESINCELASTSYNCGIRL_KEY = "playTimeSinceLastSyncGirl";
    private String ORIGINALTIMEOFFSET_KEY = "originalTimeOffset";
    private String GOLDLOSTTOPRESTIGE_KEY = "goldLostToPrestige";
    private String GOLDLOSTTOPRESTIGEGIRL_KEY = "goldLostToPrestigeGirl";
    private String DPSLOSTTOPRESTIGE_KEY = "dpsLostToPrestige";
    private String DPSLOSTTOPRESTIGEGIRL_KEY = "dpsLostToPrestigeGirl";
    private String LASTPRESTIGE_KEY = "lastPrestige";
    private String LASTPRESTIGEGIRL_KEY = "lastPrestigeGirl";
    private String UNCOLLECTEDGOLD_KEY = "uncollectedGold";
    private String UNCOLLECTEDGOLDGIRL_KEY = "uncollectedGoldGirl";
    private String CHEATCOUNT_KEY = "cheatCount";
    private String WORLD_KEY = "world";
    private String IAPPURCHASECOUNT_KEY = "iapPurchaseCount";
    private String IAPSPENDINGINUSD_KEY = "iapSpendingInUSD";
    private String IAPAPPROVEDBYAPPLEGOOGLE_KEY = "iapApprovedByAppleGoogle";
    private String ALLREWARDEDIAPS_KEY = "allRewardedIAPs";
    private String REWARDEDCUSTOMERSERVICEDIAMOND_KEY = "rewardedCustomerServiceDiamond";
    private String REWARDEDCUSTOMERSERVICERELICS_KEY = "rewardedCustomerServiceRelics";
    private String TUTORIALPROGRESS_KEY = "tutorialProgress";
    private String DUNGEONSCOMPLETED_KEY = "dungeonsCompleted";
    private String DUNGEONSTAGE_KEY = "dungeonStage";
    private String LASTDUNGEONTIME_KEY = "lastDungeonTime";
    private String LASTCOMPLETEDDUNGEONTIME_KEY = "lastCompletedDungeonTime";
    private String TOURNAMENT_KEY = "tournament";
    private String DOUBLEFAIRYTIME_KEY = "doubleFairyTime";
    private String READINBOXMESSAGES_KEY = "readInboxMessages";
    private String TT_LANGUAGE_KEY = "tt_language";
    private String HIDETOURNAMENTPANEL_KEY = "hideTournamentPanel";
    private String GAMERATING_KEY = "gameRating";
    private String ISLINKEDTOFACEBOOK_KEY = "isLinkedToFacebook";
    private String UNLOCKEDPLAYERCUSTOMIZATIONS_KEY = "unlockedPlayerCustomizations";
    private String CURRENTPLAYERCUSTOMIZATIONS_KEY = "currentPlayerCustomizations";
    private String FRIENDSMODEL_KEY = "friendsModel";
    private String FACEBOOKID_KEY = "facebookId";
    private String DAILYCLICKMINVALUE_KEY = "dailyClickMinValue";
    private String MUSIC_KEY = "music";
    private String SOUND_KEY = "sound";
    private String PUSHNOTIFICATIONS_KEY = "pushNotifications";
    private String CALCULATORMODE_KEY = "calculatorMode";
    private String OPTIONSAUTOADVANCE_KEY = "optionsAutoAdvance";
    private String OPTIONSAUTOADVANCEGIRL_KEY = "optionsAutoAdvanceGirl";
    private String OPTIONSAUTOADVANCEBOY_KEY = "optionsAutoAdvanceBoy";
    private String HASRATEDGAME_KEY = "hasRatedGame";
    private String SEENOFFLINEGOLDPANEL_KEY = "seenOfflineGoldPanel";
    private String LIKEDFACEBOOK_KEY = "likedFacebook";
    private String FOLLOWEDTWITTER_KEY = "followedTwitter";
    private String PLAYERNAME_KEY = "playerName";
    private String PLAYERNAMEGIRL_KEY = "playerNameGirl";
    private String OPTIONSFAIRYVIDEO_KEY = "optionsFairyVideo";
    private String OPTIONSMULTIPLAYERENABLED_KEY = "optionsMultiplayerEnabled";
    private String OPTIONSPERFORMANCE_KEY = "optionsPerformance";
    private String HASOPENEDFRIENDSPANEL_KEY = "hasOpenedFriendsPanel";
    private String BACKUPIAPPRODUCTIDENTIFIER_KEY = "backupIAPProductIdentifier";
    private String BACKUPIAPBASE64ENCODEDTRANSACTIONRECEIPT_KEY = "backupIAPBase64EncodedTransactionReceipt";
    private String LASTSAVEDVERSION_KEY = "lastSavedVersion";
    private String FIRSTPURCHASEMSGSHOWN_KEY = "firstPurchaseMsgShown";
    private String LASTCLOUDSAVETIME_KEY = "lastCloudSaveTime";
    private String LASTCLICKPERIOD_KEY = "lastClickPeriod";
    private String HASCLOUDSAVEEVERSYNCED_KEY = "hasCloudSaveEverSynced";
    private String CANDOSEASON2_KEY = "canDoSeason2";
    private String DRUNKENHAMMERREWARDERECEIVED_KEY = "drunkenHammerRewardeReceived";
    private String ISDEVELOPER_KEY = "isDeveloper";
    private String FIRSTVERSIONINSTALLED_KEY = "firstVersionInstalled";
    private String ONIIXTRANSFERKEY_KEY = "oniixTransferKey";
    private String SUPERPRESTIGE_KEY = "superPrestige";
    private String ACTIVETIME_KEY = "activeTime";

    public PlayerInfoSave(JSONObject obj) {
        if (obj == null) {
            populateFromNull();
            return;
        }

        this.playerId = UUID.fromString(GenericHelpers.getStringSafe(obj, PLAYERID_KEY));
        this.friendCode = GenericHelpers.getStringSafe(obj, FRIENDCODE_KEY);
        this.cleanMasterDiamonds = GenericHelpers.getIntSafe(obj, CLEANMASTERDIAMONDS_KEY);
        this.playerLevel = GenericHelpers.getIntSafe(obj, PLAYERLEVEL_KEY);
        this.playerLevelGirl = GenericHelpers.getIntSafe(obj, PLAYERLEVELGIRL_KEY);
        this.lastActiveTime = GenericHelpers.parseDateSafe("MM/dd/yyyy HH:mm:ss", GenericHelpers.getStringSafe(obj, LASTACTIVETIME_KEY));
        this.lastActiveTimeGirl = GenericHelpers.parseDateSafe("MM/dd/yyyy HH:mm:ss", GenericHelpers.getStringSafe(obj, LASTACTIVETIMEGIRL_KEY));
        this.playerGold = GenericHelpers.getDoubleSafe(obj, PLAYERGOLD_KEY);
        this.playerGoldGirl = GenericHelpers.getDoubleSafe(obj, PLAYERGOLDGIRL_KEY);
        this.playerRelics = GenericHelpers.getIntSafe(obj, PLAYERRELICS_KEY);
        this.playerRelicsGirl = GenericHelpers.getIntSafe(obj, PLAYERRELICSGIRL_KEY);
        this.playerDiamonds = GenericHelpers.getIntSafe(obj, PLAYERDIAMONDS_KEY);
        this.hasOfflineGold = GenericHelpers.getBooleanSafe(obj, HASOFFLINEGOLD_KEY, false);
        this.skipOfflineGold = GenericHelpers.getBooleanSafe(obj, SKIPOFFLINEGOLD_KEY, false);
        this.currentStage = GenericHelpers.getIntSafe(obj, CURRENTSTAGE_KEY);
        this.currentStageGirl = GenericHelpers.getIntSafe(obj, CURRENTSTAGEGIRL_KEY);
        this.unlockedStage = GenericHelpers.getIntSafe(obj, UNLOCKEDSTAGE_KEY);
        this.unlockedStageGirl = GenericHelpers.getIntSafe(obj, UNLOCKEDSTAGEGIRL_KEY);
        this.killsInWave = GenericHelpers.getIntSafe(obj, KILLSINWAVE_KEY);
        this.killsInWaveGirl = GenericHelpers.getIntSafe(obj, KILLSINWAVEGIRL_KEY);
        this.beenToLatestStage = GenericHelpers.getBooleanSafe(obj, BEENTOLATESTSTAGE_KEY, true);
        this.beenToLatestStageGirl = GenericHelpers.getBooleanSafe(obj, BEENTOLATESTSTAGEGIRL_KEY, true);
        this.signedIntoSocial = GenericHelpers.getBooleanSafe(obj, SIGNEDINTOSOCIAL_KEY, false);
        this.shouldAskToSignInSocial = GenericHelpers.getBooleanSafe(obj, SHOULDASKTOSIGNINSOCIAL_KEY, false);
        this.socialId = GenericHelpers.getStringSafe(obj, SOCIALID_KEY);
        this.artifactRelicsSpentFixed = GenericHelpers.getBooleanSafe(obj, ARTIFACTRELICSSPENTFIXED_KEY, true);
        this.nextArtifactSeed = GenericHelpers.getIntSafe(obj, NEXTARTIFACTSEED_KEY);
        this.nextArtifactSeedGirl = GenericHelpers.getIntSafe(obj, NEXTARTIFACTSEEDGIRL_KEY);
        this.cheater = GenericHelpers.getBooleanSafe(obj, CHEATER_KEY, false);
        this.cheaterReason = GenericHelpers.getStringSafe(obj, CHEATERREASON_KEY);
        this.syncCount = GenericHelpers.getIntSafe(obj, SYNCCOUNT_KEY);
        this.playTimeSinceLastSync = GenericHelpers.getDoubleSafe(obj, PLAYTIMESINCELASTSYNC_KEY);
        this.playTimeSinceLastSyncGirl = GenericHelpers.getDoubleSafe(obj, PLAYTIMESINCELASTSYNCGIRL_KEY);
        this.originalTimeOffset = GenericHelpers.getDoubleSafe(obj, ORIGINALTIMEOFFSET_KEY);
        this.goldLostToPrestige = GenericHelpers.getDoubleSafe(obj, GOLDLOSTTOPRESTIGE_KEY);
        this.goldLostToPrestigeGirl = GenericHelpers.getDoubleSafe(obj, GOLDLOSTTOPRESTIGEGIRL_KEY);
        this.dpsLostToPrestige = GenericHelpers.getDoubleSafe(obj, DPSLOSTTOPRESTIGE_KEY);
        this.dpsLostToPrestigeGirl = GenericHelpers.getDoubleSafe(obj, DPSLOSTTOPRESTIGEGIRL_KEY);
        this.uncollectedGold = GenericHelpers.getDoubleSafe(obj, UNCOLLECTEDGOLD_KEY);
        this.uncollectedGoldGirl = GenericHelpers.getDoubleSafe(obj, UNCOLLECTEDGOLDGIRL_KEY);
        this.cheatCount = GenericHelpers.getIntSafe(obj, CHEATCOUNT_KEY);
        this.world = GenericHelpers.getIntSafe(obj, WORLD_KEY);
        this.iapPurchaseCount = GenericHelpers.getIntSafe(obj, IAPPURCHASECOUNT_KEY);
        this.iapSpendingInUSD = GenericHelpers.getDoubleSafe(obj, IAPSPENDINGINUSD_KEY);
        this.iapApprovedByAppleGoogle = GenericHelpers.getIntSafe(obj, IAPAPPROVEDBYAPPLEGOOGLE_KEY);
        this.rewardedCustomerServiceDiamond = GenericHelpers.getIntSafe(obj, REWARDEDCUSTOMERSERVICEDIAMOND_KEY);
        this.rewardedCustomerServiceRelics = GenericHelpers.getIntSafe(obj, REWARDEDCUSTOMERSERVICERELICS_KEY);
        this.dungeonsCompleted = GenericHelpers.getIntSafe(obj, DUNGEONSCOMPLETED_KEY);
        this.dungeonStage = GenericHelpers.getIntSafe(obj, DUNGEONSTAGE_KEY);
        this.tt_language = GenericHelpers.getIntSafe(obj, TT_LANGUAGE_KEY);
        this.hideTournamentPanel = GenericHelpers.getBooleanSafe(obj, HIDETOURNAMENTPANEL_KEY, false);
        this.gameRating = GenericHelpers.getIntSafe(obj, GAMERATING_KEY);
        this.isLinkedToFacebook = GenericHelpers.getBooleanSafe(obj, ISLINKEDTOFACEBOOK_KEY, false);
        this.facebookId = GenericHelpers.getStringSafe(obj, FACEBOOKID_KEY);
        this.dailyClickMinValue = GenericHelpers.getIntSafe(obj, DAILYCLICKMINVALUE_KEY);
        this.music = GenericHelpers.getIntSafe(obj, MUSIC_KEY);
        this.sound = GenericHelpers.getIntSafe(obj, SOUND_KEY);
        this.pushNotifications = GenericHelpers.getBooleanSafe(obj, PUSHNOTIFICATIONS_KEY, false);
        this.calculatorMode = GenericHelpers.getBooleanSafe(obj, CALCULATORMODE_KEY, false);
        this.optionsAutoAdvance = GenericHelpers.getBooleanSafe(obj, OPTIONSAUTOADVANCE_KEY, false);
        this.optionsAutoAdvanceGirl = GenericHelpers.getBooleanSafe(obj, OPTIONSAUTOADVANCEGIRL_KEY, false);
        this.optionsAutoAdvanceBoy = GenericHelpers.getBooleanSafe(obj, OPTIONSAUTOADVANCEBOY_KEY, false);
        this.hasRatedGame = GenericHelpers.getBooleanSafe(obj, HASRATEDGAME_KEY, false);
        this.seenOfflineGoldPanel = GenericHelpers.getBooleanSafe(obj, SEENOFFLINEGOLDPANEL_KEY, false);
        this.likedFacebook = GenericHelpers.getBooleanSafe(obj, LIKEDFACEBOOK_KEY, false);
        this.followedTwitter = GenericHelpers.getBooleanSafe(obj, FOLLOWEDTWITTER_KEY, false);
        this.playerName = GenericHelpers.getStringSafe(obj, PLAYERNAME_KEY);
        this.playerNameGirl = GenericHelpers.getStringSafe(obj, PLAYERNAMEGIRL_KEY);
        this.optionsFairyVideo = GenericHelpers.getBooleanSafe(obj, OPTIONSFAIRYVIDEO_KEY, true);
        this.optionsMultiplayerEnabled = GenericHelpers.getBooleanSafe(obj, OPTIONSMULTIPLAYERENABLED_KEY, false);
        this.optionsPerformance = GenericHelpers.getIntSafe(obj, OPTIONSPERFORMANCE_KEY);
        this.hasOpenedFriendsPanel = GenericHelpers.getBooleanSafe(obj, HASOPENEDFRIENDSPANEL_KEY, false);
        this.backupIAPProductIdentifier = GenericHelpers.getStringSafe(obj, BACKUPIAPPRODUCTIDENTIFIER_KEY);
        this.backupIAPBase64EncodedTransactionReceipt = GenericHelpers.getStringSafe(obj, BACKUPIAPBASE64ENCODEDTRANSACTIONRECEIPT_KEY);
        this.lastSavedVersion = GenericHelpers.getStringSafe(obj, LASTSAVEDVERSION_KEY);
        this.firstPurchaseMsgShown = GenericHelpers.getBooleanSafe(obj, FIRSTPURCHASEMSGSHOWN_KEY, true);
        this.hasCloudSaveEverSynced = GenericHelpers.getBooleanSafe(obj, HASCLOUDSAVEEVERSYNCED_KEY, false);
        this.canDoSeason2 = GenericHelpers.getBooleanSafe(obj, CANDOSEASON2_KEY, false);
        this.drunkenHammerRewardeReceived = GenericHelpers.getBooleanSafe(obj, DRUNKENHAMMERREWARDERECEIVED_KEY, false);
        this.isDeveloper = GenericHelpers.getBooleanSafe(obj, ISDEVELOPER_KEY, false);
        this.firstVersionInstalled = GenericHelpers.getStringSafe(obj, FIRSTVERSIONINSTALLED_KEY);
        this.oniixTransferKey = GenericHelpers.getStringSafe(obj, ONIIXTRANSFERKEY_KEY);
        this.superPrestige = GenericHelpers.getStringSafe(obj, SUPERPRESTIGE_KEY);
        this.activeTime = GenericHelpers.getIntSafe(obj, ACTIVETIME_KEY);
        this.trophyProgress = new TrophyProgressSave(GenericHelpers.getJSONObjectSafe(obj, TROPHYPROGRESS_KEY));
        this.trophyProgressGirl = new TrophyProgressSave(GenericHelpers.getJSONObjectSafe(obj, TROPHYPROGRESSGIRL_KEY));
        this.artifactLevels = new ArtifactLevels(GenericHelpers.getJSONObjectSafe(obj, ARTIFACTLEVELS_KEY));
        this.artifactRelicsSpent = new ArtifactRelics(GenericHelpers.getJSONObjectSafe(obj, ARTIFACTRELICSSPENT_KEY));
        this.powerUpInventory = new PowerUpInventory(GenericHelpers.getJSONObjectSafe(obj, POWERUPINVENTORY_KEY));
        this.allRewardedIAPs = new RewardedIAPs(GenericHelpers.constructJSONObjectSafe(GenericHelpers.getStringSafe(obj, ALLREWARDEDIAPS_KEY)));
        this.tutorialProgress = new TutorialProgress(GenericHelpers.getJSONObjectSafe(obj, TUTORIALPROGRESS_KEY));
        this.unlockedPlayerCustomizations = new PlayerCustomizations(GenericHelpers.getStringSafe(obj, UNLOCKEDPLAYERCUSTOMIZATIONS_KEY));
        this.currentPlayerCustomizations = new PlayerCustomizations(GenericHelpers.getStringSafe(obj, CURRENTPLAYERCUSTOMIZATIONS_KEY));
        this.friendsModel = new Friends(GenericHelpers.getJSONObjectSafe(obj, FRIENDSMODEL_KEY));
        this.readInboxMessages = new Inbox(GenericHelpers.getJSONObjectSafe(obj, READINBOXMESSAGES_KEY));
        this.tournament = new Tournament(GenericHelpers.getJSONObjectSafe(obj, TOURNAMENT_KEY));
        this.heroSave = new HeroSave(GenericHelpers.getJSONObjectSafe(obj, HEROSAVE_KEY));
        this.abilitySave = new AbilitySave(GenericHelpers.getJSONObjectSafe(obj, ABILITYSAVE_KEY));
        this.lastPrestige = GenericHelpers.parseDateSafe("MM/dd/yyyy HH:mm:ss", GenericHelpers.getStringSafe(obj, LASTPRESTIGE_KEY));
        this.lastPrestigeGirl = GenericHelpers.parseDateSafe("MM/dd/yyyy HH:mm:ss", GenericHelpers.getStringSafe(obj, LASTPRESTIGEGIRL_KEY));
        this.lastCloudSaveTime = GenericHelpers.parseDateSafe("MM/dd/yyyy HH:mm:ss", GenericHelpers.getStringSafe(obj, LASTCLOUDSAVETIME_KEY));
        this.lastClickPeriod = GenericHelpers.parseDateSafe("MM/dd/yyyy HH:mm:ss", GenericHelpers.getStringSafe(obj, LASTCLICKPERIOD_KEY));
        this.lastDungeonTime = GenericHelpers.parseDateSafe("MM/dd/yyyy HH:mm:ss", GenericHelpers.getStringSafe(obj, LASTDUNGEONTIME_KEY));
        this.lastCompletedDungeonTime = GenericHelpers.parseDateSafe("MM/dd/yyyy HH:mm:ss", GenericHelpers.getStringSafe(obj, LASTCOMPLETEDDUNGEONTIME_KEY));
        this.doubleFairyTime = GenericHelpers.parseDateSafe("MM/dd/yyyy HH:mm:ss", GenericHelpers.getStringSafe(obj, DOUBLEFAIRYTIME_KEY));

    }

    private void populateFromNull() {
        this.playerId = UUID.fromString("00000000-0000-0000-0000-000000000000");
        this.friendCode = "";
        this.cleanMasterDiamonds = 0;
        this.playerLevel = 0;
        this.playerLevelGirl = 0;
        this.lastActiveTime = new Date(0);
        this.lastActiveTimeGirl = new Date(0);
        this.playerGold = 0;
        this.playerGoldGirl = 0;
        this.playerRelics = 0;
        this.playerRelicsGirl = 0;
        this.playerDiamonds = 0;
        this.hasOfflineGold = false;
        this.skipOfflineGold = false;
        this.currentStage = 0;
        this.currentStageGirl = 0;
        this.unlockedStage = 0;
        this.unlockedStageGirl = 0;
        this.killsInWave = 0;
        this.killsInWaveGirl = 0;
        this.beenToLatestStage = false;
        this.beenToLatestStageGirl = false;
        this.signedIntoSocial = false;
        this.shouldAskToSignInSocial = false;
        this.socialId = "";
        this.heroSave = new HeroSave(null);
        this.abilitySave = new AbilitySave(null);
        this.artifactRelicsSpentFixed = true;
        this.nextArtifactSeed = 0;
        this.nextArtifactSeedGirl = 0;
        this.cheater = false;
        this.cheaterReason = "";
        this.syncCount = 0;
        this.playTimeSinceLastSync = 0;
        this.playTimeSinceLastSyncGirl = 0;
        this.originalTimeOffset = 0;
        this.goldLostToPrestige = 0;
        this.goldLostToPrestigeGirl = 0;
        this.dpsLostToPrestige = 0;
        this.dpsLostToPrestigeGirl = 0;
        this.lastPrestige = new Date(0);
        this.lastPrestigeGirl = new Date(0);
        this.uncollectedGold = 0;
        this.uncollectedGoldGirl = 0;
        this.cheatCount = 0;
        this.world = 0;
        this.iapPurchaseCount = 0;
        this.iapSpendingInUSD = 0;
        this.iapApprovedByAppleGoogle = 0;
        this.rewardedCustomerServiceDiamond = 0;
        this.rewardedCustomerServiceRelics = 0;
        this.dungeonsCompleted = 0;
        this.dungeonStage = 0;
        this.lastDungeonTime = new Date(0);
        this.lastCompletedDungeonTime = new Date(0);
        this.tournament = new Tournament(null);
        this.doubleFairyTime = new Date(0);
        this.readInboxMessages = new Inbox(null);
        this.tt_language = 0;
        this.hideTournamentPanel = false;
        this.gameRating = 0;
        this.isLinkedToFacebook = false;
        this.unlockedPlayerCustomizations = new PlayerCustomizations(null);
        this.currentPlayerCustomizations = new PlayerCustomizations(null);
        this.friendsModel = new Friends(null);
        this.facebookId = "";
        this.dailyClickMinValue = 0;
        this.music = 0;
        this.sound = 0;
        this.pushNotifications = false;
        this.calculatorMode = false;
        this.optionsAutoAdvance = false;
        this.optionsAutoAdvanceGirl = false;
        this.optionsAutoAdvanceBoy = false;
        this.hasRatedGame = false;
        this.seenOfflineGoldPanel = false;
        this.likedFacebook = false;
        this.followedTwitter = false;
        this.playerName = "Sword Master";
        this.playerNameGirl = "Spell Master";
        this.optionsFairyVideo = true;
        this.optionsMultiplayerEnabled = false;
        this.optionsPerformance = 0;
        this.hasOpenedFriendsPanel = false;
        this.backupIAPProductIdentifier = "";
        this.backupIAPBase64EncodedTransactionReceipt = "";
        this.lastSavedVersion = "0.0";
        this.firstPurchaseMsgShown = false;
        this.lastCloudSaveTime = new Date(0);
        this.lastClickPeriod = new Date(0);
        this.hasCloudSaveEverSynced = false;
        this.canDoSeason2 = false;
        this.drunkenHammerRewardeReceived = false;
        this.isDeveloper = false;
        this.firstVersionInstalled = "0.0";
        this.oniixTransferKey = "";
        this.superPrestige = "";
        this.activeTime = 0;
        this.trophyProgress = new TrophyProgressSave(null);
        this.trophyProgressGirl = new TrophyProgressSave(null);
        this.artifactLevels = new ArtifactLevels(null);
        this.artifactRelicsSpent = new ArtifactRelics(null);
        this.powerUpInventory = new PowerUpInventory(null);
        this.allRewardedIAPs = new RewardedIAPs(null);
        this.tutorialProgress = new TutorialProgress(null);
    }

    public JSONObject generateJson(){
        JSONObject obj = new JSONObject();

        SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");

        GenericHelpers.putStringSafe(obj, PLAYERID_KEY, this.playerId.toString());
        GenericHelpers.putStringSafe(obj, FRIENDCODE_KEY, this.friendCode);
        GenericHelpers.putIntSafe(obj, CLEANMASTERDIAMONDS_KEY, this.cleanMasterDiamonds);
        GenericHelpers.putIntSafe(obj, PLAYERLEVEL_KEY, this.playerLevel);
        GenericHelpers.putIntSafe(obj, PLAYERLEVELGIRL_KEY, this.playerLevelGirl);
        GenericHelpers.putStringSafe(obj, LASTACTIVETIME_KEY, formatter.format(this.lastActiveTime));
        GenericHelpers.putStringSafe(obj, LASTACTIVETIMEGIRL_KEY, formatter.format(this.lastActiveTimeGirl));
        GenericHelpers.putDoubleSafe(obj, PLAYERGOLD_KEY, this.playerGold);
        GenericHelpers.putDoubleSafe(obj, PLAYERGOLDGIRL_KEY, this.playerGoldGirl);
        GenericHelpers.putIntSafe(obj, PLAYERRELICS_KEY, this.playerRelics);
        GenericHelpers.putIntSafe(obj, PLAYERRELICSGIRL_KEY, this.playerRelicsGirl);
        GenericHelpers.putIntSafe(obj, PLAYERDIAMONDS_KEY, this.playerDiamonds);
        GenericHelpers.putBooleanSafe(obj, HASOFFLINEGOLD_KEY, this.hasOfflineGold);
        GenericHelpers.putBooleanSafe(obj, SKIPOFFLINEGOLD_KEY, this.skipOfflineGold);
        GenericHelpers.putIntSafe(obj, CURRENTSTAGE_KEY, this.currentStage);
        GenericHelpers.putIntSafe(obj, CURRENTSTAGEGIRL_KEY, this.currentStageGirl);
        GenericHelpers.putIntSafe(obj, UNLOCKEDSTAGE_KEY, this.unlockedStage);
        GenericHelpers.putIntSafe(obj, UNLOCKEDSTAGEGIRL_KEY, this.unlockedStageGirl);
        GenericHelpers.putIntSafe(obj, KILLSINWAVE_KEY, this.killsInWave);
        GenericHelpers.putIntSafe(obj, KILLSINWAVEGIRL_KEY, this.killsInWaveGirl);
        GenericHelpers.putBooleanSafe(obj, BEENTOLATESTSTAGE_KEY, this.beenToLatestStage);
        GenericHelpers.putBooleanSafe(obj, BEENTOLATESTSTAGEGIRL_KEY, this.beenToLatestStageGirl);
        GenericHelpers.putBooleanSafe(obj, SIGNEDINTOSOCIAL_KEY, this.signedIntoSocial);
        GenericHelpers.putBooleanSafe(obj, SHOULDASKTOSIGNINSOCIAL_KEY, this.shouldAskToSignInSocial);
        GenericHelpers.putStringSafe(obj, SOCIALID_KEY, this.socialId);
        GenericHelpers.putBooleanSafe(obj, ARTIFACTRELICSSPENTFIXED_KEY, this.artifactRelicsSpentFixed);
        GenericHelpers.putIntSafe(obj, NEXTARTIFACTSEED_KEY, this.nextArtifactSeed);
        GenericHelpers.putIntSafe(obj, NEXTARTIFACTSEEDGIRL_KEY, this.nextArtifactSeedGirl);
        GenericHelpers.putBooleanSafe(obj, CHEATER_KEY, this.cheater);
        GenericHelpers.putStringSafe(obj, CHEATERREASON_KEY, this.cheaterReason);
        GenericHelpers.putIntSafe(obj, SYNCCOUNT_KEY, this.syncCount);
        GenericHelpers.putDoubleSafe(obj, PLAYTIMESINCELASTSYNC_KEY, this.playTimeSinceLastSync);
        GenericHelpers.putDoubleSafe(obj, PLAYTIMESINCELASTSYNCGIRL_KEY, this.playTimeSinceLastSyncGirl);
        GenericHelpers.putDoubleSafe(obj, ORIGINALTIMEOFFSET_KEY, this.originalTimeOffset);
        GenericHelpers.putDoubleSafe(obj, GOLDLOSTTOPRESTIGE_KEY, this.goldLostToPrestige);
        GenericHelpers.putDoubleSafe(obj, GOLDLOSTTOPRESTIGEGIRL_KEY, this.goldLostToPrestigeGirl);
        GenericHelpers.putDoubleSafe(obj, DPSLOSTTOPRESTIGE_KEY, this.dpsLostToPrestige);
        GenericHelpers.putDoubleSafe(obj, DPSLOSTTOPRESTIGEGIRL_KEY, this.dpsLostToPrestigeGirl);
        GenericHelpers.putDoubleSafe(obj, UNCOLLECTEDGOLD_KEY, this.uncollectedGold);
        GenericHelpers.putDoubleSafe(obj, UNCOLLECTEDGOLDGIRL_KEY, this.uncollectedGoldGirl);
        GenericHelpers.putIntSafe(obj, CHEATCOUNT_KEY, this.cheatCount);
        GenericHelpers.putIntSafe(obj, WORLD_KEY, this.world);
        GenericHelpers.putIntSafe(obj, IAPPURCHASECOUNT_KEY, this.iapPurchaseCount);
        GenericHelpers.putDoubleSafe(obj, IAPSPENDINGINUSD_KEY, this.iapSpendingInUSD);
        GenericHelpers.putIntSafe(obj, IAPAPPROVEDBYAPPLEGOOGLE_KEY, this.iapApprovedByAppleGoogle);
        GenericHelpers.putIntSafe(obj, REWARDEDCUSTOMERSERVICEDIAMOND_KEY, this.rewardedCustomerServiceDiamond);
        GenericHelpers.putIntSafe(obj, REWARDEDCUSTOMERSERVICERELICS_KEY, this.rewardedCustomerServiceRelics);
        GenericHelpers.putIntSafe(obj, DUNGEONSCOMPLETED_KEY, this.dungeonsCompleted);
        GenericHelpers.putIntSafe(obj, DUNGEONSTAGE_KEY, this.dungeonStage);
        GenericHelpers.putIntSafe(obj, TT_LANGUAGE_KEY, this.tt_language);
        GenericHelpers.putBooleanSafe(obj, HIDETOURNAMENTPANEL_KEY, this.hideTournamentPanel);
        GenericHelpers.putIntSafe(obj, GAMERATING_KEY, this.gameRating);
        GenericHelpers.putBooleanSafe(obj, ISLINKEDTOFACEBOOK_KEY, this.isLinkedToFacebook);
        GenericHelpers.putStringSafe(obj, FACEBOOKID_KEY, this.facebookId);
        GenericHelpers.putIntSafe(obj, DAILYCLICKMINVALUE_KEY, this.dailyClickMinValue);
        GenericHelpers.putIntSafe(obj, MUSIC_KEY, this.music);
        GenericHelpers.putIntSafe(obj, SOUND_KEY, this.sound);
        GenericHelpers.putBooleanSafe(obj, PUSHNOTIFICATIONS_KEY, this.pushNotifications);
        GenericHelpers.putBooleanSafe(obj, CALCULATORMODE_KEY, this.calculatorMode);
        GenericHelpers.putBooleanSafe(obj, OPTIONSAUTOADVANCE_KEY, this.optionsAutoAdvance);
        GenericHelpers.putBooleanSafe(obj, OPTIONSAUTOADVANCEGIRL_KEY, this.optionsAutoAdvanceGirl);
        GenericHelpers.putBooleanSafe(obj, OPTIONSAUTOADVANCEBOY_KEY, this.optionsAutoAdvanceBoy);
        GenericHelpers.putBooleanSafe(obj, HASRATEDGAME_KEY, this.hasRatedGame);
        GenericHelpers.putBooleanSafe(obj, SEENOFFLINEGOLDPANEL_KEY, this.seenOfflineGoldPanel);
        GenericHelpers.putBooleanSafe(obj, LIKEDFACEBOOK_KEY, this.likedFacebook);
        GenericHelpers.putBooleanSafe(obj, FOLLOWEDTWITTER_KEY, this.followedTwitter);
        GenericHelpers.putStringSafe(obj, PLAYERNAME_KEY, this.playerName);
        GenericHelpers.putStringSafe(obj, PLAYERNAMEGIRL_KEY, this.playerNameGirl);
        GenericHelpers.putBooleanSafe(obj, OPTIONSFAIRYVIDEO_KEY, this.optionsFairyVideo);
        GenericHelpers.putBooleanSafe(obj, OPTIONSMULTIPLAYERENABLED_KEY, this.optionsMultiplayerEnabled);
        GenericHelpers.putIntSafe(obj, OPTIONSPERFORMANCE_KEY, this.optionsPerformance);
        GenericHelpers.putBooleanSafe(obj, HASOPENEDFRIENDSPANEL_KEY, hasOpenedFriendsPanel);
        GenericHelpers.putStringSafe(obj, BACKUPIAPPRODUCTIDENTIFIER_KEY, this.backupIAPProductIdentifier);
        GenericHelpers.putStringSafe(obj, BACKUPIAPBASE64ENCODEDTRANSACTIONRECEIPT_KEY, this.backupIAPBase64EncodedTransactionReceipt);
        GenericHelpers.putStringSafe(obj, LASTSAVEDVERSION_KEY, this.lastSavedVersion);
        GenericHelpers.putBooleanSafe(obj, FIRSTPURCHASEMSGSHOWN_KEY, this.firstPurchaseMsgShown);
        GenericHelpers.putBooleanSafe(obj, HASCLOUDSAVEEVERSYNCED_KEY, this.hasCloudSaveEverSynced);
        GenericHelpers.putBooleanSafe(obj, CANDOSEASON2_KEY, this.canDoSeason2);
        GenericHelpers.putBooleanSafe(obj, DRUNKENHAMMERREWARDERECEIVED_KEY, this.drunkenHammerRewardeReceived);
        GenericHelpers.putBooleanSafe(obj, ISDEVELOPER_KEY, this.isDeveloper);
        GenericHelpers.putStringSafe(obj, FIRSTVERSIONINSTALLED_KEY, this.firstVersionInstalled);
        GenericHelpers.putStringSafe(obj, ONIIXTRANSFERKEY_KEY, this.ONIIXTRANSFERKEY_KEY);
        GenericHelpers.putStringSafe(obj, SUPERPRESTIGE_KEY, this.SUPERPRESTIGE_KEY);
        GenericHelpers.putIntSafe(obj, ACTIVETIME_KEY, this.activeTime);
        GenericHelpers.putJSONObjectSafe(obj, TROPHYPROGRESS_KEY, this.trophyProgress.generateJson());
        GenericHelpers.putJSONObjectSafe(obj, TROPHYPROGRESSGIRL_KEY, this.trophyProgressGirl.generateJson());
        GenericHelpers.putJSONObjectSafe(obj, ARTIFACTLEVELS_KEY, this.artifactLevels.generateJson());
        GenericHelpers.putJSONObjectSafe(obj, ARTIFACTRELICSSPENT_KEY, this.artifactRelicsSpent.generateJson());
        GenericHelpers.putJSONObjectSafe(obj, POWERUPINVENTORY_KEY, this.powerUpInventory.generateJson());
        GenericHelpers.putStringSafe(obj, ALLREWARDEDIAPS_KEY, this.allRewardedIAPs.generateJson().toString());
        GenericHelpers.putJSONObjectSafe(obj, TUTORIALPROGRESS_KEY, this.tutorialProgress.generateJson());
        GenericHelpers.putStringSafe(obj, UNLOCKEDPLAYERCUSTOMIZATIONS_KEY, this.unlockedPlayerCustomizations.getString());
        GenericHelpers.putStringSafe(obj, CURRENTPLAYERCUSTOMIZATIONS_KEY, this.currentPlayerCustomizations.getString());
        GenericHelpers.putJSONObjectSafe(obj, FRIENDSMODEL_KEY, this.friendsModel.generateJson());
        GenericHelpers.putJSONObjectSafe(obj, READINBOXMESSAGES_KEY, this.readInboxMessages.generateJson());
        GenericHelpers.putJSONObjectSafe(obj, TOURNAMENT_KEY, this.tournament.generateJson());
        GenericHelpers.putJSONObjectSafe(obj, HEROSAVE_KEY, this.heroSave.generateJson());
        GenericHelpers.putJSONObjectSafe(obj, ABILITYSAVE_KEY, this.abilitySave.generateJson());
        GenericHelpers.putStringSafe(obj, LASTPRESTIGE_KEY, formatter.format(this.lastPrestige));
        GenericHelpers.putStringSafe(obj, LASTPRESTIGEGIRL_KEY, formatter.format(this.lastPrestigeGirl));
        GenericHelpers.putStringSafe(obj, LASTCLOUDSAVETIME_KEY, formatter.format(this.lastCloudSaveTime));
        GenericHelpers.putStringSafe(obj, LASTCLICKPERIOD_KEY, formatter.format(this.lastClickPeriod));
        GenericHelpers.putStringSafe(obj, LASTDUNGEONTIME_KEY, formatter.format(this.lastDungeonTime));
        GenericHelpers.putStringSafe(obj, LASTCOMPLETEDDUNGEONTIME_KEY, formatter.format(this.lastCompletedDungeonTime));
        GenericHelpers.putStringSafe(obj, DOUBLEFAIRYTIME_KEY, formatter.format(this.doubleFairyTime));

        return obj;
    }
}
